import { Role } from "@/lib/auth/protected-routes";
import { DashCard } from "../store/constants/dash-cards/types";
const allRoles: Role[] = [
  "user",
  "super-admin",
  "hr",
  "super-admin",
  "employee",
  "hr-manager",
  "org-admin",
  "manager",
  "admin",
];
export const allModules: DashCard[] = [
  {
    title: "HR Hub",
    description: "People and recruitment tools",
    icon: "🏢",
    href: "/hr",
    rolesAllowed: ["hr", "super-admin", "hr-manager", "manager", "admin"],
    allRolesAllowed: false,
    color: "#00796b",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: true,
  },
  {
    title: "Employees",
    description: "Manage employee information and records",
    icon: "🧑‍💼",
    href: "/hr/employees",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
  },
  {
    title: "Payroll",
    description: "Process payroll and manage salaries",
    icon: "💰",
    href: "/hr/payroll",
    rolesAllowed: ["hr", "hr-manager", "super-admin"],
    allRolesAllowed: false,
    color: "#673ab7",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
  },
  {
    title: "Time Off",
    description: "Manage employee time off requests",
    icon: "🌴",
    href: "/employee-portal/leaves",
    rolesAllowed: [
      "hr",
      "hr-manager",
      "employee",
      "manager",
      "admin",
      "super-admin",
    ],
    allRolesAllowed: false,
    color: "#ff8f00",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
  },
  {
    title: "POS",
    description: "Point of Sale operations",
    icon: "🛒",
    href: "/pos",
    rolesAllowed: ["admin", "super-admin", "manager", "user"],
    allRolesAllowed: false,
    color: "#d84315",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: true,
  },
  {
    title: "Inventory",
    description: "Manage product inventory and stock",
    icon: "📦",
    href: "/inventory",
    rolesAllowed: ["admin", "super-admin", "manager"],
    allRolesAllowed: false,
    color: "#00695c",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "POS",
  },
  {
    title: "Reports",
    description: "View analytics and reports",
    icon: "📊",
    href: "/dashboard/#",
    rolesAllowed: ["super-admin"],
    allRolesAllowed: false,
    color: "#512da8",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: true,
  },
  {
    title: "Support Center",
    description: "Resolve customer tickets",
    icon: "🎧",
    href: "/dashboard/support",
    rolesAllowed: ["super-admin", "support"],
    allRolesAllowed: false,
    color: "#0288d1",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: true,
  },
  {
    title: "Profile",
    description: "Customize your profile",
    icon: "👤",
    href: "/employee-portal",
    rolesAllowed: [
      "user",
      "super-admin",
      "hr",
      "employee",
      "hr-manager",
      "org-admin",
      "manager",
      "admin",
    ],
    allRolesAllowed: true,
    color: "#6a1b9a",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
  },
  {
    title: "Organization Settings",
    description: "Customize your organization settings",
    icon: "⚙️",
    href: "/dashboard/organization-settings",
    rolesAllowed: ["super-admin", "org-admin", "admin"],
    allRolesAllowed: false,
    color: "#424242",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: true,
  },
  {
    title: "Achievements",
    description: "Track milestones and badges",
    icon: "🏆",
    href: "/employee-portal",
    rolesAllowed: allRoles,
    allRolesAllowed: true,
    color: "#f9a825",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "Profile",
  },
  {
    title: "Learning Center",
    description: "Access training materials",
    icon: "📘",
    href: "/dashboard",
    rolesAllowed: allRoles,
    allRolesAllowed: true,
    color: "#3949ab",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: true,
  },
  {
    title: "Super Admin",
    description: "Manage system-wide settings",
    icon: "🛡️",
    href: "/dashboard/super-admin",
    rolesAllowed: ["super-admin"],
    allRolesAllowed: false,
    color: "#d32f2f",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: true,
  },
  {
    title: "Users",
    description: "Organization users management",
    icon: "🧑‍🤝‍🧑",
    href: "/users",
    rolesAllowed: ["org-admin", "super-admin", "admin"],
    allRolesAllowed: false,
    color: "#00796b",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "Organization Settings",
  },
];
