import {z} from "zod"
export const MilestoneFormSchema = z.object({
  id: z.string().optional().nullable(),
  title: z.string({ error: "Title is required" }),
  code: z.string({ error: "Code is required" }),
  approvalStatus: z.enum(["Draft", "Pending", "Approved", "Rejected"], { error: "Approval status is required" }).default("Draft"),
  approvalRequired: z.boolean({ error: "Approval required is required" }).default(false),
  billable: z.boolean({ error: "Billable is required" }).default(true),
  billingAmount: z.coerce.number().optional().nullable(),
  percentCompletion: z.coerce.number().optional().nullable(),
  plannedStartDate: z.coerce.date().optional().nullable(),
  plannedEndDate: z.coerce.date().optional().nullable(),
  actualCompletionDate: z.coerce.date().optional().nullable(),
  description: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  billingSchedule: z.string().optional().nullable(),
  assignedTeamOrDept: z.string().optional().nullable(),
  responsibleOwner: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  createdBy: z.string().optional().nullable(),
  updatedBy: z.string().optional().nullable(),
  deliverables: z.unknown().optional().nullable(),
  notificationsPolicy: z.unknown().optional().nullable(),
  predecessors: z.unknown().optional().nullable(),
  attachments: z.array(z.unknown()).meta({ url: "/attachments" }).optional().nullable(),
  comments: z.array(z.unknown()).meta({ url: "/comments" }).optional().nullable(),
})