export type NavItem = {
  link: string;
  hub: string;
  module?: string;
  category?: string;
  entity?: string;
  name: string;
  emojie: string;
  description?: string;
  active?: boolean;
};

export const sales_links: NavItem[] = [
  {
    link: "#",
    hub: "Sales",
    module: undefined,
    category: "module",
    entity: undefined,
    name: "Sales",
    emojie: "💼",
    description: "Manage leads and sales operations.",
    active: false,
  },
  {
    link: "#",
    hub: "Sales",
    module: "CRM",
    category: "module",
    entity: undefined,
    name: "CRM",
    emojie: "🤝",
    description: "Customer Relationship Management",
    active: false,
  },
  {
    link: "#",
    hub: "Sales",
    module: "Sales Management",
    category: "module",
    entity: undefined,
    name: "Sales Management",
    emojie: "📈",
    description: "Manage sales lifecycle and pipelines",
    active: false,
  },
];

export const pos_links: NavItem[] = [
  {
    link: "#",
    hub: "POS",
    module: undefined,
    category: "module",
    entity: undefined,
    name: "POS",
    emojie: "🛒",
    description: "Point of Sale solutions for various sectors.",
    active: false,
  },
  {
    link: "#",
    hub: "POS",
    module: "Entertainment & Hospitality POS",
    category: "module",
    entity: undefined,
    name: "Entertainment & Hospitality POS",
    emojie: "🥳",
    description: "POS for entertainment and hospitality",
    active: false,
  },
  {
    link: "#",
    hub: "POS",
    module: "Retail Sector POS",
    category: "module",
    entity: undefined,
    name: "Retail Sector POS",
    emojie: "🛍️",
    description: "POS for retail businesses",
    active: false,
  },
  {
    link: "#",
    hub: "POS",
    module: "Transportation & Travel POS",
    category: "module",
    entity: undefined,
    name: "Transportation & Travel POS",
    emojie: "✈️",
    description: "POS for transport and travel",
    active: false,
  },
  {
    link: "#",
    hub: "POS",
    module: "Wholesale & Distribution POS",
    category: "module",
    entity: undefined,
    name: "Wholesale & Distribution POS",
    emojie: "📦",
    description: "POS for wholesale and distribution",
    active: false,
  },
  {
    link: "#",
    hub: "POS",
    module: "Service Industry POS",
    category: "module",
    entity: undefined,
    name: "Service Industry POS",
    emojie: "🛎️",
    description: "POS for service industries",
    active: false,
  },
  {
    link: "#",
    hub: "POS",
    module: "Pharmaceuticals",
    category: "module",
    entity: undefined,
    name: "Pharmaceuticals",
    emojie: "💊",
    description: "POS for pharmaceutical sector",
    active: false,
  },
  {
    link: "#",
    hub: "POS",
    module: "Food & Beverage POS",
    category: "module",
    entity: undefined,
    name: "Food & Beverage POS",
    emojie: "🍔",
    description: "POS for food and beverage businesses",
    active: false,
  },
];

export const asset_links: NavItem[] = [
  {
    link: "#",
    hub: "Assets",
    module: undefined,
    category: "module",
    entity: undefined,
    name: "Assets",
    emojie: "🏢",
    description: "Track and manage company assets.",
    active: false,
  },
  {
    link: "#",
    hub: "Assets",
    module: "Fixed Asset Management",
    category: "module",
    entity: undefined,
    name: "Fixed Asset Management",
    emojie: "🏗️",
    description: "Manage fixed assets lifecycle",
    active: false,
  },
  {
    link: "#",
    hub: "Assets",
    module: "Fleet Management",
    category: "module",
    entity: undefined,
    name: "Fleet Management",
    emojie: "🚚",
    description: "Track and maintain company vehicles",
    active: false,
  },
  {
    link: "#",
    hub: "Assets",
    module: "Maintenance Management",
    category: "module",
    entity: undefined,
    name: "Maintenance Management",
    emojie: "🔧",
    description: "Schedule and track asset maintenance",
    active: false,
  },
];

export const website_links: NavItem[] = [
  {
    link: "#",
    hub: "Website",
    module: undefined,
    category: "module",
    entity: undefined,
    name: "Website",
    emojie: "🌐",
    description: "Website builder and CMS tools.",
    active: false,
  },
  {
    link: "#",
    hub: "Website",
    module: "CMS",
    category: "module",
    entity: undefined,
    name: "CMS",
    emojie: "📝",
    description: "Manage website content",
    active: false,
  },
];

export const scm_links: NavItem[] = [
  {
    link: "#",
    hub: "SCM",
    module: undefined,
    category: "module",
    entity: undefined,
    name: "SCM",
    emojie: "🔗",
    description: "Supply chain management tools.",
    active: false,
  },
  {
    link: "#",
    hub: "SCM",
    module: "Inventory Management",
    category: "module",
    entity: undefined,
    name: "Inventory Management",
    emojie: "📦",
    description: "Track inventory levels and movement",
    active: false,
  },
  {
    link: "#",
    hub: "SCM",
    module: "Manufacturing",
    category: "module",
    entity: undefined,
    name: "Manufacturing",
    emojie: "🏭",
    description: "Manage production processes",
    active: false,
  },
  {
    link: "#",
    hub: "SCM",
    module: "Procurement",
    category: "module",
    entity: undefined,
    name: "Procurement",
    emojie: "🧾",
    description: "Manage purchasing and suppliers",
    active: false,
  },
  {
    link: "#",
    hub: "SCM",
    module: "Product Management",
    category: "module",
    entity: undefined,
    name: "Product Management",
    emojie: "🏷️",
    description: "Organize and define product catalog",
    active: false,
  },
  {
    link: "#",
    hub: "SCM",
    module: "Cost Accounting Management",
    category: "module",
    entity: undefined,
    name: "Cost Accounting Management",
    emojie: "💵",
    description: "Analyze and control costs",
    active: false,
  },
];

export const finance_links: NavItem[] = [
  {
    link: "#",
    hub: "Finance",
    module: undefined,
    category: "module",
    entity: undefined,
    name: "Finance",
    emojie: "💰",
    description: "Accounting and financial operations.",
    active: false,
  },
  {
    link: "#",
    hub: "Finance",
    module: "General Ledger (GL)",
    category: "module",
    entity: undefined,
    name: "General Ledger (GL)",
    emojie: "📘",
    description: "Track financial transactions",
    active: false,
  },
  {
    link: "#",
    hub: "Finance",
    module: "Accounts Payable (AP)",
    category: "module",
    entity: undefined,
    name: "Accounts Payable (AP)",
    emojie: "📤",
    description: "Track outgoing payments",
    active: false,
  },
  {
    link: "#",
    hub: "Finance",
    module: "Accounts Receivable (AR)",
    category: "module",
    entity: undefined,
    name: "Accounts Receivable (AR)",
    emojie: "📥",
    description: "Track incoming payments",
    active: false,
  },
  {
    link: "#",
    hub: "Finance",
    module: "Bank & Cash Management",
    category: "module",
    entity: undefined,
    name: "Bank & Cash Management",
    emojie: "🏦",
    description: "Manage bank accounts and cash flow",
    active: false,
  },
  {
    link: "#",
    hub: "Finance",
    module: "Budgeting",
    category: "module",
    entity: undefined,
    name: "Budgeting",
    emojie: "🔖",
    description: "Plan and control budgets",
    active: false,
  },
];

export const campus_links: NavItem[] = [
  {
    link: "#",
    hub: "CampusHub",
    module: undefined,
    category: "module",
    entity: undefined,
    name: "CampusHub",
    emojie: "🎓",
    description:
      "Manage student, academic, attendance, finance, and self-service portals.",
    active: false,
  },
  {
    link: "#",
    hub: "CampusHub",
    module: "Student Information Management (SIM)",
    category: "module",
    entity: undefined,
    name: "Student Information Management (SIM)",
    emojie: "🧑‍🎓",
    description:
      "Centralized system for managing all student-related data across their lifecycle",
    active: false,
  },
  {
    link: "#",
    hub: "CampusHub",
    module: "Learning Management System (LMS)",
    category: "module",
    entity: undefined,
    name: "Learning Management System (LMS)",
    emojie: "📚",
    description:
      "Platform for delivering, managing, and tracking learning content",
    active: false,
  },
  {
    link: "#",
    hub: "CampusHub",
    module: "Academic Management",
    category: "module",
    entity: undefined,
    name: "Academic Management",
    emojie: "🏫",
    description:
      "Course catalog, timetable, syllabus mapping, exam scheduling, grading, transcript generation",
    active: false,
  },
  {
    link: "#",
    hub: "CampusHub",
    module: "Attendance Management",
    category: "module",
    entity: undefined,
    name: "Attendance Management",
    emojie: "✅",
    description:
      "Daily/period attendance, absence approvals, alerts, integration with timetable",
    active: false,
  },
  {
    link: "#",
    hub: "CampusHub",
    module: "Fee & Finance Management",
    category: "module",
    entity: undefined,
    name: "Fee & Finance Management",
    emojie: "🪙",
    description:
      "Tuition structure, invoicing, scholarships/discounts, fee collection",
    active: false,
  },
  {
    link: "#",
    hub: "CampusHub",
    module: "Self-service Portals",
    category: "module",
    entity: undefined,
    name: "Self-service Portals",
    emojie: "💻",
    description:
      "Student, parent, and teacher portals for accessing grades, schedules, fees, and messages",
    active: false,
  },
];

export const ai_links: NavItem[] = [
  {
    link: "#",
    hub: "AI",
    module: undefined,
    category: "module",
    entity: undefined,
    name: "AI",
    emojie: "🧠",
    description: "AI-powered tools for business optimization.",
    active: false,
  },
  {
    link: "#",
    hub: "AI",
    module: "Data Analysis & Forecasting",
    category: "module",
    entity: undefined,
    name: "Data Analysis & Forecasting",
    emojie: "🔮",
    description: "Analyze data and predict future trends",
    active: false,
  },
  {
    link: "#",
    hub: "AI",
    module: "Automation of Routine Tasks",
    category: "module",
    entity: undefined,
    name: "Automation of Routine Tasks",
    emojie: "🤖",
    description: "Automate repetitive tasks and workflows",
    active: false,
  },
  {
    link: "#",
    hub: "AI",
    module: "Intelligent Recommendations",
    category: "module",
    entity: undefined,
    name: "Intelligent Recommendations",
    emojie: "💡",
    description: "Provide smart recommendations based on user behavior",
    active: false,
  },
  {
    link: "#",
    hub: "AI",
    module: "Conversational Assistance",
    category: "module",
    entity: undefined,
    name: "Conversational Assistance",
    emojie: "💬",
    description: "Engage users with a conversational AI assistant",
    active: false,
  },
  {
    link: "#",
    hub: "AI",
    module: "Anomaly & Risk Detection",
    category: "module",
    entity: undefined,
    name: "Anomaly & Risk Detection",
    emojie: "🚨",
    description: "Detect unusual patterns and potential risks",
    active: false,
  },
  {
    link: "#",
    hub: "AI",
    module: "Decision Support",
    category: "module",
    entity: undefined,
    name: "Decision Support",
    emojie: "🎯",
    description: "Assist with data-driven decision making",
    active: false,
  },
];

export const inActiveLinks = [
  ...ai_links,
  ...scm_links,
  ...finance_links,
  ...pos_links,
  ...sales_links,
  ...campus_links,
  ...website_links,
  ...asset_links,
];
