import { NavItem } from "./nav-items-utils";

export const hrLinks: NavItem[] = [
  {
    link: "/hr",
    hub: "hr",
    name: "Hr",
    emojie: "🏢",
    category: "navigation",
    description:
      "The main human resources administration hub for managing all HR functions.",
    active: true,
  },
  {
    link: "/hr/attendance",
    hub: "hr",
    module: "attendance",
    name: "Attendance",
    emojie: "⌚",
    category: "attendance",
    description:
      "Overview and access to all attendance and time-keeping management tools.",
    active: true,
  },
  {
    link: "/hr/attendance/attendance",
    hub: "hr",
    module: "attendance",
    entity: "attendance",
    name: "Attendance",
    emojie: "⏰",
    category: "attendance",
    description:
      "Detailed view and management of employee attendance records and logs.",
    active: true,
  },
  {
    link: "/hr/attendance/work-entry",
    hub: "hr",
    module: "attendance",
    entity: "work entry",
    name: "Work Entry",
    emojie: "⏰",
    category: "attendance",
    description: "Manual Work Entry.",
    active: true,
  },
  {
    link: "/hr/attendance/worked-day-entry",
    hub: "hr",
    module: "attendance",
    entity: "worked day entry",
    name: "Worked Day Entry",
    emojie: "⏰",
    category: "attendance",
    description: "Manual Work day Entry.",
    active: true,
  },
  {
    link: "/hr/attendance/attendance-device",
    hub: "hr",
    module: "attendance",
    entity: "attendance-device",
    name: "Attendance Device",
    emojie: "📱",
    category: "settings",
    description:
      "Configuration and management of attendance tracking devices and integrations.",
    active: true,
  },
  {
    link: "/hr/attendance/ot-policy",
    hub: "hr",
    module: "attendance",
    entity: "ot-policy",
    name: "OT Policy",
    emojie: "📱",
    category: "settings",
    description: "Configuration and management of overtime policy.",
    active: true,
  },
  {
    link: "/hr/attendance/attendance-rule-approver",
    hub: "hr",
    module: "attendance",
    entity: "attendance-rule-approver",
    name: "Attendance Rule Approver",
    emojie: "🧑‍⚖️",
    category: "settings",
    description:
      "Set up and manage the approval hierarchy for attendance exceptions and rules.",
    active: true,
  },
  {
    link: "/hr/attendance/attendance-rules",
    hub: "hr",
    module: "attendance",
    entity: "attendance-rules",
    name: "Attendance Rules",
    emojie: "⚖️",
    category: "settings",
    description:
      "Define and maintain organizational rules for attendance, clocking, and grace periods.",
    active: true,
  },
  {
    link: "/hr/attendance/attendance/test",
    hub: "hr",
    module: "attendance",
    entity: "test",
    name: "Test",
    emojie: "🧪",
    category: "testing",
    description:
      "Testing environment for attendance functionalities and new configurations.",
    active: true,
  },
  {
    link: "/hr/attendance/method-setup",
    hub: "hr",
    module: "attendance",
    entity: "method-setup",
    name: "Method Setup",
    emojie: "🛠️",
    category: "settings",
    description:
      "Configuration of different attendance tracking methods (e.g., biometric, mobile, web).",
    active: true,
  },
  {
    link: "/hr/attendance/overtime",
    hub: "hr",
    module: "attendance",
    entity: "overtime",
    name: "Overtime",
    emojie: "⏳",
    category: "attendance",
    description:
      "Management and approval of employee overtime requests and records.",
    active: true,
  },
  {
    link: "/hr/attendance/work-schedule",
    hub: "hr",
    module: "attendance",
    entity: "work-schedule",
    name: "Work Schedule",
    emojie: "🗓️",
    category: "settings",
    description:
      "Create and assign standard or flexible work schedules for employees and teams.",
    active: true,
  },
  {
    link: "/hr/attendance/work-schedule-slot",
    hub: "hr",
    module: "attendance",
    entity: "work-schedule-slot",
    name: "Work Schedule Slot",
    emojie: "🕒",
    category: "settings",
    description:
      "Define specific time slots and shift details within a work schedule.",
    active: true,
  },
  {
    link: "/hr/compliance",
    hub: "hr",
    module: "compliance",
    name: "Compliance",
    emojie: "🛡️",
    category: "compliance",
    description:
      "Overview and management of regulatory and internal compliance mandates.",
    active: true,
  },
  {
    link: "/hr/compliance/compliance",
    hub: "hr",
    module: "compliance",
    entity: "compliance",
    name: "Compliance",
    emojie: "✔️",
    category: "compliance",
    description:
      "Tracking and status of all current organizational compliance efforts.",
    active: true,
  },
  {
    link: "/hr/compliance/compliance-audit",
    hub: "hr",
    module: "compliance",
    entity: "compliance-audit",
    name: "Compliance Audit",
    emojie: "🔎",
    category: "compliance",
    description: "Schedule, perform, and review results of compliance audits.",
    active: true,
  },
  {
    link: "/hr/compliance/compliance-requirement",
    hub: "hr",
    module: "compliance",
    entity: "compliance-requirement",
    name: "Compliance Requirement",
    emojie: "📜",
    category: "compliance",
    description:
      "Define and document specific legal and internal compliance requirements.",
    active: true,
  },
  {
    link: "/hr/compliance/compliance-task",
    hub: "hr",
    module: "compliance",
    entity: "compliance-task",
    name: "Compliance Task",
    emojie: "✅",
    category: "compliance",
    description:
      "Assign and track the completion of tasks related to compliance requirements.",
    active: true,
  },
  {
    link: "/hr/employees",
    hub: "hr",
    module: "employees",
    name: "Employees",
    emojie: "👨‍💼",
    category: "employees",
    description:
      "Central module for managing all employee data, records, and lifecycle.",
    active: true,
  },
  {
    link: "/hr/employees/contracts",
    hub: "hr",
    module: "employees",
    entity: "contracts",
    name: "Contracts",
    emojie: "🤝",
    category: "employees",
    description:
      "Management and storage of employee employment contracts and agreements.",
    active: true,
  },
  {
    link: "/hr/employees/contract-component",
    hub: "hr",
    module: "employees",
    entity: "contract component",
    name: "Contracts components",
    emojie: "🤝",
    category: "employees",
    description: "Management and  employment contracts components.",
    active: true,
  },
  {
    link: "/hr/employees/documents",
    hub: "hr",
    module: "employees",
    entity: "documents",
    name: "Documents",
    emojie: "📜",
    category: "employees",
    description:
      "Repository for all employee-related official documents and records.",
    active: true,
  },
  {
    link: "/hr/employees/employees",
    hub: "hr",
    module: "employees",
    entity: "employees",
    name: "Employees",
    emojie: "👥",
    category: "employees",
    description:
      "A directory and detailed list of all current and past employees.",
    active: true,
  },
  {
    link: "/hr/employees/exit-survey",
    hub: "hr",
    module: "employees",
    entity: "exit-survey",
    name: "Exit Survey",
    emojie: "👋",
    category: "offboarding",
    description:
      "Design and management of surveys for employees leaving the organization.",
    active: true,
  },
  {
    link: "/hr/employees/exit-survey-response",
    hub: "hr",
    module: "employees",
    entity: "exit-survey-response",
    name: "Exit Survey Response",
    emojie: "💬",
    category: "offboarding",
    description:
      "Review and analysis of collected employee exit survey responses.",
    active: true,
  },
  {
    link: "/hr/employees/offboarding-question",
    hub: "hr",
    module: "employees",
    entity: "offboarding-question",
    name: "Offboarding Question",
    emojie: "❓",
    category: "settings",
    description:
      "Define the set of questions used in offboarding checklists and interviews.",
    active: true,
  },
  {
    link: "/hr/employees/offboarding-request",
    hub: "hr",
    module: "employees",
    entity: "offboarding-request",
    name: "Offboarding Request",
    emojie: "📤",
    category: "offboarding",
    description:
      "Initiate and track the process for employee separation or termination.",
    active: true,
  },
  {
    link: "/hr/employees/offboarding-task",
    hub: "hr",
    module: "employees",
    entity: "offboarding-task",
    name: "Offboarding Task",
    emojie: "⚙️",
    category: "offboarding",
    description:
      "Management of individual tasks required to complete an employee offboarding process.",
    active: true,
  },
  {
    link: "/hr/employees/offboarding-template",
    hub: "hr",
    module: "employees",
    entity: "offboarding-template",
    name: "Offboarding Template",
    emojie: "📄",
    category: "settings",
    description:
      "Create and manage standardized templates for the offboarding process.",
    active: true,
  },
  {
    link: "/hr/employees/settings",
    hub: "hr",
    module: "employees",
    entity: "settings",
    name: "Settings",
    emojie: "🔧",
    category: "settings",
    description:
      "Configuration settings for employee profiles, fields, and access.",
    active: true,
  },
  {
    link: "/hr/leave",
    hub: "hr",
    module: "leave",
    name: "Leave",
    emojie: "🏖️",
    category: "leave",
    description:
      "Centralized system for managing all types of employee leave, absence, and holidays.",
    active: true,
  },
  {
    link: "/hr/leave/leave-balance",
    hub: "hr",
    module: "leave",
    entity: "leave-balance",
    name: "Leave Balance",
    emojie: "⚖️",
    category: "leave",
    description:
      "Monitor and manage the current leave balances for all employees.",
    active: true,
  },
  {
    link: "/hr/leave/leave-encashment",
    hub: "hr",
    module: "leave",
    entity: "leave-encashment",
    name: "Leave Encashment",
    emojie: "💲",
    category: "leave",
    description: "Process and track requests for leave encashment and payout.",
    active: true,
  },
  {
    link: "/hr/leave/leave-request",
    hub: "hr",
    module: "leave",
    entity: "leave-request",
    name: "Leave Request",
    emojie: "📬",
    category: "leave",
    description: "Review, approve, or reject pending employee leave requests.",
    active: true,
  },
  {
    link: "/hr/leave/settings",
    hub: "hr",
    module: "leave",
    entity: "settings",
    name: "Settings",
    emojie: "🔧",
    category: "settings",
    description:
      "Core configuration for leave module rules, accruals, and policies.",
    active: true,
  },
  {
    link: "/hr/leave/settings/holiday",
    hub: "hr",
    module: "leave",
    entity: "holiday",
    name: "Holiday",
    emojie: "🥳",
    category: "settings",
    description: "Define and manage the official public and company holidays.",
    active: true,
  },
  {
    link: "/hr/leave/settings/leave-type",
    hub: "hr",
    module: "leave",
    entity: "leave-type",
    name: "Leave Type",
    emojie: "🏷️",
    category: "settings",
    description:
      "Customize and manage different categories of leave (e.g., sick, annual, parental).",
    active: true,
  },
  {
    link: "/hr/leave/settings/work-schedule",
    hub: "hr",
    module: "leave",
    entity: "work-schedule",
    name: "Work Schedule",
    emojie: "🗓️",
    category: "settings",
    description:
      "Define and manage the work calendars and schedules for leave calculation.",
    active: true,
  },
  {
    link: "/hr/leave/settings/work-schedule-slot",
    hub: "hr",
    module: "leave",
    entity: "work-schedule-slot",
    name: "Work Schedule Slot",
    emojie: "🕒",
    category: "settings",
    description:
      "Detailed setup of working time slots within various work schedules.",
    active: true,
  },
  {
    link: "/hr/leave/sick-leave-episode",
    hub: "hr",
    module: "leave",
    entity: "sick-leave-episode",
    name: "Sick Leave Episode",
    emojie: "🤒",
    category: "leave",
    description:
      "Track and manage extended sick leave periods and associated documentation.",
    active: true,
  },
  {
    link: "/hr/payroll",
    hub: "hr",
    module: "payroll",
    name: "Payroll",
    emojie: "💳",
    category: "payroll",
    description:
      "The core module for processing salaries, wages, and all financial compensation.",
    active: true,
  },
  {
    link: "/hr/payroll/bank-accounts",
    hub: "hr",
    module: "payroll",
    entity: "bank-accounts",
    name: "Bank Accounts",
    emojie: "🏦",
    category: "payroll",
    description:
      "Manage and verify employee bank account details for salary disbursement.",
    active: true,
  },
  {
    link: "/hr/payroll/generate-single-payslip",
    hub: "hr",
    module: "payroll",
    entity: "generate-single-payslip",
    name: "Generate Single Payslip",
    emojie: "🖨️",
    category: "payroll",
    description:
      "Process and generate an individual payslip for a specific employee.",
    active: true,
  },
  {
    link: "/hr/payroll/payroll-batches",
    hub: "hr",
    module: "payroll",
    entity: "payroll-batches",
    name: "Payroll Batches",
    emojie: "📦",
    category: "payroll",
    description:
      "Manage and process groups of payslips in distinct payroll batches.",
    active: true,
  },
  {
    link: "/hr/payroll/payslip-inputs",
    hub: "hr",
    module: "payroll",
    entity: "payslip-inputs",
    name: "Payslip Inputs",
    emojie: "⌨️",
    category: "payroll",
    description:
      "Enter and manage variable inputs (e.g., bonuses, deductions) for payslip calculation.",
    active: true,
  },
  {
    link: "/hr/payroll/payslips",
    hub: "hr",
    module: "payroll",
    entity: "payslips",
    name: "Payslips",
    emojie: "💵",
    category: "payroll",
    description: "Archive and manage all generated employee payslips.",
    active: true,
  },
  {
    link: "/hr/payroll/pension-policy",
    hub: "hr",
    module: "payroll",
    entity: "pension-policy",
    name: "Pension Policy",
    emojie: "👴",
    category: "settings",
    description:
      "Configuration and management of employee pension and retirement policies.",
    active: true,
  },
  {
    link: "/hr/payroll/report",
    hub: "hr",
    module: "payroll",
    entity: "report",
    name: "Report",
    emojie: "📈",
    category: "reporting",
    description:
      "Generate and analyze various reports related to payroll and compensation.",
    active: true,
  },
  {
    link: "/hr/payroll/settings/periods",
    hub: "hr",
    module: "payroll",
    entity: "periods",
    name: "Periods",
    emojie: "📅",
    category: "settings",
    description:
      "Define and manage the fiscal and payroll calculation periods.",
    active: true,
  },
  {
    link: "/hr/payroll/settings/salary-rule-categories",
    hub: "hr",
    module: "payroll",
    entity: "salary-rule-categories",
    name: "Salary Rule Categories",
    emojie: "🏷️",
    category: "settings",
    description:
      "Categorize and group salary rules for easier management and reporting.",
    active: true,
  },
  {
    link: "/hr/payroll/settings/salary-rules",
    hub: "hr",
    module: "payroll",
    entity: "salary-rules",
    name: "Salary Rules",
    emojie: "📜",
    category: "settings",
    description:
      "Define the calculation logic and formulas for various salary components.",
    active: true,
  },
  {
    link: "/hr/payroll/settings/salary-structure",
    hub: "hr",
    module: "payroll",
    entity: "salary-structure",
    name: "Salary Structure",
    emojie: "🏗️",
    category: "settings",
    description:
      "Create and manage overall salary frameworks and compensation structures.",
    active: true,
  },
  {
    link: "/hr/payroll/settings/salary-structure-rules",
    hub: "hr",
    module: "payroll",
    entity: "salary-structure-rules",
    name: "Salary Structure Rules",
    emojie: "🧱",
    category: "settings",
    description: "Link specific salary rules to different salary structures.",
    active: true,
  },
  {
    link: "/hr/payroll/tax-bracket",
    hub: "hr",
    module: "payroll",
    entity: "tax-bracket",
    name: "Tax Bracket",
    emojie: "🔢",
    category: "settings",
    description:
      "Define and manage governmental tax brackets and rates for payroll deduction.",
    active: true,
  },
  {
    link: "/hr/payroll/work-entries",
    hub: "hr",
    module: "payroll",
    entity: "work-entries",
    name: "Work Entries",
    emojie: "📝",
    category: "payroll",
    description:
      "Review and process recorded work hours and entries used for payroll calculation.",
    active: true,
  },
  {
    link: "/hr/performance",
    hub: "hr",
    module: "performance",
    name: "Performance",
    emojie: "🚀",
    category: "performance",
    description:
      "Module for planning, tracking, and evaluating employee performance.",
    active: true,
  },
  {
    link: "/hr/performance/appraisalevaluation",
    hub: "hr",
    module: "performance",
    entity: "appraisalevaluation",
    name: "Appraisalevaluation",
    emojie: "⭐",
    category: "performance",
    description: "Conduct and finalize performance appraisals and evaluations.",
    active: true,
  },
  {
    link: "/hr/performance/appraisalplan",
    hub: "hr",
    module: "performance",
    entity: "appraisalplan",
    name: "Appraisalplan",
    emojie: "🗺️",
    category: "performance",
    description:
      "Define the schedule and steps for annual or cycle-based performance appraisal plans.",
    active: true,
  },
  {
    link: "/hr/performance/benefitplan",
    hub: "hr",
    module: "performance",
    entity: "benefitplan",
    name: "Benefitplan",
    emojie: "🛡️",
    category: "settings",
    description:
      "Define the structure and terms of various employee benefit programs.",
    active: true,
  },
  {
    link: "/hr/performance/employeebenefit",
    hub: "hr",
    module: "performance",
    entity: "employeebenefit",
    name: "Employeebenefit",
    emojie: "🍎",
    category: "performance",
    description:
      "Manage individual employee enrollment and utilization of benefits.",
    active: true,
  },
  {
    link: "/hr/performance/goal",
    hub: "hr",
    module: "performance",
    entity: "goal",
    name: "Goal",
    emojie: "🎯",
    category: "performance",
    description:
      "Set, track, and manage employee and organizational performance goals.",
    active: true,
  },
  {
    link: "/hr/performance/incident",
    hub: "hr",
    module: "performance",
    entity: "incident",
    name: "Incident",
    emojie: "🚨",
    category: "performance",
    description:
      "Log and track workplace incidents, disciplinary issues, and safety events.",
    active: true,
  },
  {
    link: "/hr/performance/incidentaction",
    hub: "hr",
    module: "performance",
    entity: "incidentaction",
    name: "Incidentaction",
    emojie: "🛑",
    category: "settings",
    description:
      "Define the possible corrective or disciplinary actions for logged incidents.",
    active: true,
  },
  {
    link: "/hr/performance/incidentstatus",
    hub: "hr",
    module: "performance",
    entity: "incidentstatus",
    name: "Incidentstatus",
    emojie: "🚥",
    category: "settings",
    description:
      "Manage the different lifecycle statuses for a recorded incident (e.g., reported, under review, closed).",
    active: true,
  },
  {
    link: "/hr/performance/incidenttype",
    hub: "hr",
    module: "performance",
    entity: "incidenttype",
    name: "Incidenttype",
    emojie: "⚡",
    category: "settings",
    description:
      "Categorize and manage the types of workplace incidents (e.g., safety, misconduct, harassment).",
    active: true,
  },
  {
    link: "/hr/performance/kpi",
    hub: "hr",
    module: "performance",
    entity: "kpi",
    name: "Kpi",
    emojie: "💯",
    category: "performance",
    description:
      "Define and track Key Performance Indicators (KPIs) for roles and employees.",
    active: true,
  },
  {
    link: "/hr/performance/objective",
    hub: "hr",
    module: "performance",
    entity: "objective",
    name: "Objective",
    emojie: "🥅",
    category: "performance",
    description:
      "Detailed management of specific business or developmental objectives.",
    active: true,
  },
  {
    link: "/hr/performance/performancecycle",
    hub: "hr",
    module: "performance",
    entity: "performancecycle",
    name: "Performancecycle",
    emojie: "🔄",
    category: "performance",
    description:
      "Define and manage the start and end dates for performance review cycles.",
    active: true,
  },
  {
    link: "/hr/performance/recommendation-rule",
    hub: "hr",
    module: "performance",
    entity: "recommendation-rule",
    name: "Recommendation Rule",
    emojie: "💡",
    category: "settings",
    description:
      "Set up rules for automated recommendations based on performance data.",
    active: true,
  },
  {
    link: "/hr/performance/template",
    hub: "hr",
    module: "performance",
    entity: "template",
    name: "Template",
    emojie: "📑",
    category: "settings",
    description:
      "Create and customize templates for performance reviews and appraisal forms.",
    active: true,
  },
];
