import { NavItem } from "./nav-items-utils";

export const selfServiceLinks: NavItem[] = [
  {
    link: "/self-service",
    hub: "self-service",
    name: "Self Service",
    emojie: "👤",
    category: "navigation",
    description:
      "The main dashboard and entry point for all self-service functionalities.",
    active: true,
  },
  {
    link: "/self-service/appraisal-evaluation",
    hub: "self-service",
    module: "performance",
    entity: "appraisal-evaluation",
    name: "Appraisal Evaluation",
    emojie: "📝",
    category: "performance",
    description:
      "Access and review your performance appraisal and evaluation documents.",
    active: true,
  },
  {
    link: "/self-service/appraisal-evaluation",
    hub: "self-service",
    module: "performance",
    name: "performance",
    emojie: "📝",
    category: "performance",
    description:
      "Overview and access to all performance management tools and features.",
    active: true,
  },
  {
    link: "/self-service/attendance",
    hub: "self-service",
    module: "attendance",
    entity: "attendance",
    name: "Attendance",
    emojie: "⏰",
    category: "attendance",
    description:
      "View and manage your daily attendance, clock-in/out records, and logs.",
    active: true,
  },
  {
    link: "/self-service/attendance",
    hub: "self-service",
    module: "attendance",
    name: "Attendance",
    emojie: "⏰",
    category: "attendance",
    description:
      "Access to the main attendance tracking module for clocking and review.",
    active: true,
  },
  {
    link: "/self-service/benefits",
    hub: "self-service",
    module: "employee",
    entity: "benefits",
    name: "Benefits",
    emojie: "🎁",
    category: "employee",
    description:
      "Explore and manage your current employee benefits and compensation packages.",
    active: true,
  },
  {
    link: "/self-service/benefits",
    hub: "self-service",
    module: "employee",
    name: "employee",
    emojie: "🎁",
    category: "employee",
    description:
      "General section for employee-related information and self-management.",
    active: true,
  },
  {
    link: "/self-service/documents",
    hub: "self-service",
    module: "employee",
    entity: "documents",
    name: "Documents",
    emojie: "📜",
    category: "employee",
    description:
      "Access and download important employment documents and files.",
    active: true,
  },
  {
    link: "/self-service/exits",
    hub: "self-service",
    module: "employee",
    entity: "exits",
    name: "Exits",
    emojie: "🚪",
    category: "employee",
    description:
      "Process or track employee exit procedures and related documentation.",
    active: true,
  },
  {
    link: "/self-service/job-req",
    hub: "self-service",
    module: "employee",
    entity: "job-req",
    name: "Job Req",
    emojie: "💼",
    category: "employee",
    description:
      "Submit or view status of job requisition requests within the company.",
    active: true,
  },
  {
    link: "/self-service/jobs",
    hub: "self-service",
    module: "employee",
    entity: "jobs",
    name: "Jobs",
    emojie: "🔍",
    category: "employee",
    description:
      "Browse and apply for internal job openings and career opportunities.",
    active: true,
  },
  {
    link: "/self-service/leaves",
    hub: "self-service",
    module: "leave",
    name: "leave",
    emojie: "🌴",
    category: "leave",
    description:
      "Main area for managing all types of leave requests and balances.",
    active: true,
  },
  {
    link: "/self-service/leaves",
    hub: "self-service",
    module: "leave",
    entity: "leaves",
    name: "Leaves",
    emojie: "🌴",
    category: "leave",
    description:
      "Request, track, and view details of your approved and pending leaves.",
    active: true,
  },
  {
    link: "/self-service/payslips",
    hub: "self-service",
    module: "payroll",
    name: "payroll",
    emojie: "💵",
    category: "payroll",
    description: "Access the payroll system and general payment information.",
    active: true,
  },
  {
    link: "/self-service/payslips",
    hub: "self-service",
    module: "payroll",
    entity: "payslips",
    name: "Payslips",
    emojie: "💵",
    category: "payroll",
    description: "View and download your monthly and historical payslips.",
    active: true,
  },
  {
    link: "/self-service/personal-info",
    hub: "self-service",
    module: "employee",
    entity: "personal-info",
    name: "Personal Info",
    emojie: "ℹ️",
    category: "employee",
    description: "Review and update your personal and contact information.",
    active: true,
  },
  {
    link: "/self-service/profile",
    hub: "self-service",
    module: "employee",
    entity: "profile",
    name: "Profile",
    emojie: "🌟",
    category: "employee",
    description:
      "Your comprehensive employee profile, including skills and experience.",
    active: true,
  },
  {
    link: "/self-service/survey",
    hub: "self-service",
    module: "training",
    name: "training",
    emojie: "📋",
    category: "training",
    description:
      "Main hub for training resources, courses, and related activities.",
    active: true,
  },
  {
    link: "/self-service/survey",
    hub: "self-service",
    module: "training",
    entity: "survey",
    name: "Survey",
    emojie: "📋",
    category: "training",
    description: "Participate in employee surveys and feedback forms.",
    active: true,
  },
  {
    link: "/self-service/training-performance",
    hub: "self-service",
    module: "training",
    entity: "training-performance",
    name: "Training Performance",
    emojie: "🎓",
    category: "training",
    description:
      "Monitor your progress and performance in assigned training programs.",
    active: true,
  },
];
