import { NavItem } from "./nav-items-utils";

export const trainingModulabs: NavItem[] = [
  {
    link: "/hr/training",
    hub: "hr",
    module: "training",
    name: "Training",
    emojie: "🎓",
    category: "training",
    description:
      "Main module for managing all employee development, learning, and training activities.",
    active: true,
  },
  {
    link: "/hr/training/settings/tna-survey-template",
    hub: "hr",
    module: "training",
    entity: "tna-survey-template",
    name: "TNA Survey Template",
    emojie: "📋",
    category: "settings",
    description:
      "Templates for Training Needs Analysis (TNA) surveys to assess skill gaps.",
    active: true,
  },
  {
    link: "/hr/training/tna-answer",
    hub: "hr",
    module: "training",
    entity: "tna-answer",
    name: "TNA Answer",
    emojie: "💬",
    category: "training",
    description:
      "Review and analyze collected responses from Training Needs Analysis surveys.",
    active: true,
  },
  {
    link: "/hr/training/tna-question",
    hub: "hr",
    module: "training",
    entity: "tna-question",
    name: "TNA Question",
    emojie: "❓",
    category: "training",
    description:
      "Define and manage the question bank for Training Needs Analysis surveys.",
    active: true,
  },
  {
    link: "/hr/training/tna-survey",
    hub: "hr",
    module: "training",
    entity: "tna-survey",
    name: "TNA Survey",
    emojie: "📝",
    category: "training",
    description:
      "Management and distribution of live Training Needs Analysis surveys to employees.",
    active: true,
  },
  {
    link: "/hr/training/trainer",
    hub: "hr",
    module: "training",
    entity: "trainer",
    name: "Trainer",
    emojie: "👨‍🏫",
    category: "training",
    description:
      "Database and management of internal and external training facilitators/instructors.",
    active: true,
  },
  {
    link: "/hr/training/training-attendance",
    hub: "hr",
    module: "training",
    entity: "training-attendance",
    name: "Training Attendance",
    emojie: "✅",
    category: "training",
    description:
      "Record and track employee attendance for training sessions and courses.",
    active: true,
  },
  {
    link: "/hr/training/training-certificate",
    hub: "hr",
    module: "training",
    entity: "training-certificate",
    name: "Training Certificate",
    emojie: "🏅",
    category: "training",
    description:
      "Generate, issue, and manage certificates of completion for training programs.",
    active: true,
  },
  {
    link: "/hr/training/training-program-plan",
    hub: "hr",
    module: "training",
    entity: "training-program-plan",
    name: "Training Program Plan",
    emojie: "🗺️",
    category: "training",
    description:
      "Design and schedule comprehensive plans for long-term training programs.",
    active: true,
  },
  {
    link: "/hr/training/training-record",
    hub: "hr",
    module: "training",
    entity: "training-record",
    name: "Training Record",
    emojie: "📜",
    category: "training",
    description: "Archive of all historical training completed by employees.",
    active: true,
  },
  {
    link: "/hr/training/training-request",
    hub: "hr",
    module: "training",
    entity: "training-request",
    name: "Training Request",
    emojie: "📧",
    category: "training",
    description:
      "Review and manage employee-submitted requests for new or external training.",
    active: true,
  },
  {
    link: "/hr/training/training-request-appraisal-evaluation",
    hub: "hr",
    module: "training",
    entity: "training-request-appraisal-evaluation",
    name: "Training Request Appraisal Evaluation",
    emojie: "📊",
    category: "training",
    description:
      "Evaluate training requests based on employee performance appraisal data.",
    active: true,
  },
  {
    link: "/hr/training/training-request-bundle",
    hub: "hr",
    module: "training",
    entity: "training-request-bundle",
    name: "Training Request Bundle",
    emojie: "📦",
    category: "training",
    description:
      "Group and process multiple related training requests together.",
    active: true,
  },
  {
    link: "/hr/training/training-request-category",
    hub: "hr",
    module: "training",
    entity: "training-request-category",
    name: "Training Request Category",
    emojie: "🏷️",
    category: "training",
    description: "Categorize training requests by topic, skill, or department.",
    active: true,
  },
  {
    link: "/hr/training/training-request-target-employee",
    hub: "hr",
    module: "training",
    entity: "training-request-target-employee",
    name: "Training Request Target Employee",
    emojie: "🎯",
    category: "training",
    description:
      "Identify and manage the specific employees who are the focus of a training request.",
    active: true,
  },
  {
    link: "/hr/training/training-request-tna",
    hub: "hr",
    module: "training",
    entity: "training-request-tna",
    name: "Training Request TNA",
    emojie: "📝",
    category: "training",
    description:
      "Link training requests to specific needs identified in the TNA process.",
    active: true,
  },
  {
    link: "/hr/training/training-session",
    hub: "hr",
    module: "training",
    entity: "training-session",
    name: "Training Session",
    emojie: "📅",
    category: "training",
    description:
      "Schedule, manage logistics, and run individual training sessions or classes.",
    active: true,
  },
  {
    link: "/hr/training/training-session-trainer",
    hub: "hr",
    module: "training",
    entity: "training-session-trainer",
    name: "Training Session Trainer",
    emojie: "👤",
    category: "training",
    description:
      "Assign and track the trainers responsible for specific training sessions.",
    active: true,
  },
];
