import { DashCard } from "./types";

export const allDashCards: DashCard[] = [
  {
    title: "Sales Dashboard",
    description: "Overview of sales performance",
    icon: "📈",
    href: "/sales",
    rolesAllowed: ["sales", "admin"],
    allRolesAllowed: false,
    color: "#4caf50",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Inventory Management",
    description: "Track inventory levels and movements",
    icon: "📦",
    href: "/inventory",
    rolesAllowed: ["inventory", "admin"],
    allRolesAllowed: false,
    color: "#ff9800",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Purchase Orders",
    description: "Manage purchase orders and vendors",
    icon: "🛒",
    href: "/purchase-orders",
    rolesAllowed: ["purchase", "admin"],
    allRolesAllowed: false,
    color: "#3f51b5",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Inventory Management",
  },
  {
    title: "Vendor Management",
    description: "Manage vendors and contracts",
    icon: "🏢",
    href: "/vendors",
    rolesAllowed: ["purchase", "admin"],
    allRolesAllowed: false,
    color: "#009688",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Inventory Management",
  },
  {
    title: "HR Dashboard",
    description: "Human resources overview",
    icon: "👥",
    href: "/hr",
    rolesAllowed: ["hr", "admin"],
    allRolesAllowed: false,
    color: "#e91e63",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Employee Records",
    description: "Manage employee data and documents",
    icon: "📋",
    href: "/employees",
    rolesAllowed: ["hr", "admin"],
    allRolesAllowed: false,
    color: "#9c27b0",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "HR Dashboard",
  },
  {
    title: "Payroll",
    description: "Manage employee salaries and payments",
    icon: "💰",
    href: "/payroll",
    rolesAllowed: ["hr", "finance", "admin"],
    allRolesAllowed: false,
    color: "#ff5722",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: true,
    otherScenario: false,
    parentModule: "HR Dashboard",
  },
  {
    title: "Finance Dashboard",
    description: "Financial overview and reports",
    icon: "💹",
    href: "/finance",
    rolesAllowed: ["finance", "admin"],
    allRolesAllowed: false,
    color: "#607d8b",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Budgeting",
    description: "Create and manage budgets",
    icon: "📊",
    href: "/budgeting",
    rolesAllowed: ["finance", "admin"],
    allRolesAllowed: false,
    color: "#3f51b5",
    isActive: true,
    isSubscribed: false,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Finance Dashboard",
  },
  {
    title: "Expense Tracking",
    description: "Track and approve expenses",
    icon: "🧾",
    href: "/expenses",
    rolesAllowed: ["finance", "admin"],
    allRolesAllowed: false,
    color: "#795548",
    isActive: false,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Finance Dashboard",
  },
  {
    title: "Project Management",
    description: "Track project progress and tasks",
    icon: "📅",
    href: "/projects",
    rolesAllowed: ["project-manager", "admin"],
    allRolesAllowed: false,
    color: "#2196f3",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Task Management",
    description: "Manage tasks and deadlines",
    icon: "✅",
    href: "/tasks",
    rolesAllowed: ["project-manager", "team-member", "admin"],
    allRolesAllowed: false,
    color: "#4caf50",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Project Management",
  },
  {
    title: "Timesheets",
    description: "Track employee time on projects",
    icon: "⏰",
    href: "/timesheets",
    rolesAllowed: ["project-manager", "team-member", "hr", "admin"],
    allRolesAllowed: false,
    color: "#03a9f4",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Project Management",
  },
  {
    title: "Customer Relationship",
    description: "Manage customer data and interactions",
    icon: "🤝",
    href: "/crm",
    rolesAllowed: ["sales", "admin"],
    allRolesAllowed: false,
    color: "#ff5722",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Leads",
    description: "Track and manage sales leads",
    icon: "📋",
    href: "/leads",
    rolesAllowed: ["sales", "admin"],
    allRolesAllowed: false,
    color: "#f44336",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Customer Relationship",
  },
  {
    title: "Opportunities",
    description: "Manage sales opportunities",
    icon: "🎯",
    href: "/opportunities",
    rolesAllowed: ["sales", "admin"],
    allRolesAllowed: false,
    color: "#9c27b0",
    isActive: true,
    isSubscribed: false,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Customer Relationship",
  },
  {
    title: "Marketing",
    description: "Manage marketing campaigns",
    icon: "📢",
    href: "/marketing",
    rolesAllowed: ["marketing", "admin"],
    allRolesAllowed: false,
    color: "#ff9800",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Campaigns",
    description: "Create and monitor campaigns",
    icon: "📊",
    href: "/campaigns",
    rolesAllowed: ["marketing", "admin"],
    allRolesAllowed: false,
    color: "#673ab7",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Marketing",
  },
  {
    title: "Email Marketing",
    description: "Manage email campaigns",
    icon: "✉️",
    href: "/email-marketing",
    rolesAllowed: ["marketing", "admin"],
    allRolesAllowed: false,
    color: "#2196f3",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Marketing",
  },
  {
    title: "Support Desk",
    description: "Manage customer support tickets",
    icon: "🎫",
    href: "/support",
    rolesAllowed: ["support", "admin"],
    allRolesAllowed: false,
    color: "#009688",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: true,
    otherScenario: false,
  },
  {
    title: "Tickets",
    description: "Track support tickets and resolutions",
    icon: "🛠️",
    href: "/tickets",
    rolesAllowed: ["support", "admin"],
    allRolesAllowed: false,
    color: "#4caf50",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Support Desk",
  },
  {
    title: "Knowledge Base",
    description: "Self-help documentation",
    icon: "📚",
    href: "/knowledge-base",
    rolesAllowed: ["support", "user", "admin"],
    allRolesAllowed: false,
    color: "#3f51b5",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Support Desk",
  },
  {
    title: "Settings",
    description: "System settings and configuration",
    icon: "⚙️",
    href: "/settings",
    rolesAllowed: ["admin"],
    allRolesAllowed: true,
    color: "#607d8b",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "User Management",
    description: "Manage users and permissions",
    icon: "👤",
    href: "/users",
    rolesAllowed: ["admin"],
    allRolesAllowed: true,
    color: "#9e9e9e",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Settings",
  },
  {
    title: "Roles & Permissions",
    description: "Configure roles and permissions",
    icon: "🔐",
    href: "/roles",
    rolesAllowed: ["admin"],
    allRolesAllowed: true,
    color: "#ff5722",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Settings",
  },
  {
    title: "Audit Logs",
    description: "View system audit logs",
    icon: "📜",
    href: "/audit-logs",
    rolesAllowed: ["admin"],
    allRolesAllowed: true,
    color: "#795548",
    isActive: true,
    isSubscribed: false,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Settings",
  },
  {
    title: "Notifications",
    description: "Manage system notifications",
    icon: "🔔",
    href: "/notifications",
    rolesAllowed: ["admin"],
    allRolesAllowed: true,
    color: "#2196f3",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Reports",
    description: "Generate and view reports",
    icon: "📑",
    href: "/#",
    rolesAllowed: ["admin", "finance", "sales"],
    allRolesAllowed: false,
    color: "#009688",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Sales Reports",
    description: "Reports related to sales data",
    icon: "📈",
    href: "/reports/sales",
    rolesAllowed: ["sales", "admin"],
    allRolesAllowed: false,
    color: "#4caf50",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Reports",
  },
  {
    title: "Finance Reports",
    description: "Reports related to finance data",
    icon: "💹",
    href: "/reports/finance",
    rolesAllowed: ["finance", "admin"],
    allRolesAllowed: false,
    color: "#607d8b",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Reports",
  },
  {
    title: "HR Reports",
    description: "Reports related to HR data",
    icon: "👥",
    href: "/reports/hr",
    rolesAllowed: ["hr", "admin"],
    allRolesAllowed: false,
    color: "#e91e63",
    isActive: true,
    isSubscribed: false,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Reports",
  },
  {
    title: "Audit Reports",
    description: "Audit and compliance reports",
    icon: "📜",
    href: "/reports/audit",
    rolesAllowed: ["admin"],
    allRolesAllowed: true,
    color: "#795548",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Reports",
  },
  {
    title: "Dashboard Widgets",
    description: "Configure dashboard widgets",
    icon: "🧩",
    href: "/widgets",
    rolesAllowed: ["admin", "user"],
    allRolesAllowed: false,
    color: "#673ab7",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Widget Gallery",
    description: "Available dashboard widgets",
    icon: "🖼️",
    href: "/widgets/gallery",
    rolesAllowed: ["admin", "user"],
    allRolesAllowed: false,
    color: "#3f51b5",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Dashboard Widgets",
  },
  {
    title: "Widget Settings",
    description: "Customize widget settings",
    icon: "⚙️",
    href: "/widgets/settings",
    rolesAllowed: ["admin", "user"],
    allRolesAllowed: false,
    color: "#009688",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Dashboard Widgets",
  },
  {
    title: "API Management",
    description: "Manage API keys and usage",
    icon: "🔑",
    href: "/api",
    rolesAllowed: ["admin", "developer"],
    allRolesAllowed: false,
    color: "#607d8b",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "API Keys",
    description: "Manage individual API keys",
    icon: "🗝️",
    href: "/api/keys",
    rolesAllowed: ["admin", "developer"],
    allRolesAllowed: false,
    color: "#3f51b5",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "API Management",
  },
  {
    title: "API Logs",
    description: "View API usage logs",
    icon: "📜",
    href: "/api/logs",
    rolesAllowed: ["admin", "developer"],
    allRolesAllowed: false,
    color: "#795548",
    isActive: true,
    isSubscribed: false,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "API Management",
  },
  {
    title: "System Health",
    description: "Monitor system status and alerts",
    icon: "❤️‍🩹",
    href: "/system-health",
    rolesAllowed: ["admin", "devops"],
    allRolesAllowed: false,
    color: "#f44336",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Server Status",
    description: "Monitor server uptime and performance",
    icon: "🖥️",
    href: "/system-health/server",
    rolesAllowed: ["admin", "devops"],
    allRolesAllowed: false,
    color: "#2196f3",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "System Health",
  },
  {
    title: "Error Logs",
    description: "View application error logs",
    icon: "❗",
    href: "/system-health/errors",
    rolesAllowed: ["admin", "devops"],
    allRolesAllowed: false,
    color: "#ff9800",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: true,
    otherScenario: false,
    parentModule: "System Health",
  },
  {
    title: "Security",
    description: "Manage system security settings",
    icon: "🔒",
    href: "/security",
    rolesAllowed: ["admin", "security"],
    allRolesAllowed: false,
    color: "#9c27b0",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Access Control",
    description: "Configure access control policies",
    icon: "🛡️",
    href: "/security/access-control",
    rolesAllowed: ["admin", "security"],
    allRolesAllowed: false,
    color: "#673ab7",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Security",
  },
  {
    title: "Threat Detection",
    description: "Monitor threats and vulnerabilities",
    icon: "🚨",
    href: "/security/threats",
    rolesAllowed: ["admin", "security"],
    allRolesAllowed: false,
    color: "#f44336",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: true,
    otherScenario: false,
    parentModule: "Security",
  },
  {
    title: "Compliance",
    description: "Manage compliance and audits",
    icon: "📋",
    href: "/compliance",
    rolesAllowed: ["admin", "compliance"],
    allRolesAllowed: false,
    color: "#009688",
    isActive: true,
    isSubscribed: true,
    isSubModule: false,
    underMaintainance: false,
    otherScenario: false,
  },
  {
    title: "Audit Trails",
    description: "Track changes and access",
    icon: "📜",
    href: "/compliance/audit-trails",
    rolesAllowed: ["admin", "compliance"],
    allRolesAllowed: false,
    color: "#795548",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Compliance",
  },
  {
    title: "Policy Management",
    description: "Manage compliance policies",
    icon: "📑",
    href: "/compliance/policies",
    rolesAllowed: ["admin", "compliance"],
    allRolesAllowed: false,
    color: "#3f51b5",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: false,
    parentModule: "Compliance",
  },
];
