import { Role } from "@/lib/auth/protected-routes";
import { DashCard } from "./types";

const allRoles: Role[] = [
  "user",
  "super-admin",
  "hr",
  "super-admin",
  "employee",
  "hr-manager",
  "org-admin",
  "manager",
  "admin",
];

export const hrDashCards: DashCard[] = [
  {
    title: "Employees",
    description: "Manage employee information and records",
    icon: "🧑‍💼",
    href: "/hr/employees",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Recruitment",
    description: "Handle hiring and candidate processes",
    icon: "📋",
    href: "/hr/recruitment",
    rolesAllowed: ["hr", "hr-manager", "super-admin", "admin"],
    allRolesAllowed: false,
    color: "#00897b",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Payroll",
    description: "Process payroll and manage salaries",
    icon: "💰",
    href: "/hr/payroll",
    rolesAllowed: ["hr", "hr-manager", "super-admin"],
    allRolesAllowed: false,
    color: "#673ab7",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "premium",
  },
  {
    title: "Attendance",
    description: "Track employee attendance",
    icon: "📅",
    href: "/hr/attendance",
    rolesAllowed: ["hr", "manager", "hr-manager", "super-admin"],
    allRolesAllowed: false,
    color: "#5e35b1",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "starter",
  },
  {
    title: "Performance",
    description: "Review employee performance",
    icon: "📈",
    href: "/hr/performance",
    rolesAllowed: ["hr", "manager", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#f4511e",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "premium",
  },
  {
    title: "Leave",
    description: "Leave application and approvals",
    icon: "📝",
    href: "/hr/leave",
    rolesAllowed: ["employee", "hr", "manager", "hr-manager", "admin"],
    allRolesAllowed: false,
    color: "#c2185b",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "starter",
  },
  {
    title: "Training",
    description: "Plan and track employee trainings",
    icon: "🎓",
    href: "/hr/training",
    rolesAllowed: ["hr", "hr-manager", "super-admin", "manager"],
    allRolesAllowed: false,
    color: "#1976d2",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
];
