import { Role } from "@/lib/auth/protected-routes";
import { DashCard } from "./types";

const allRoles: Role[] = [
  "user",
  "super-admin",
  "hr",
  "super-admin",
  "employee",
  "hr-manager",
  "org-admin",
  "manager",
  "admin",
];

export const hrHubCards: DashCard[] = [
  {
    title: "Benefit Plans",
    description: "Benefit Plans",
    icon: "💰",
    href: "/hr/hub/benefit-plans",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Disciplinary Action",
    description: "Disciplinary Action",
    icon: "⚖️",
    href: "/hr/hub/disp-action",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Goals",
    description: "Goals",
    icon: "🎯",
    href: "/hr/hub/goal",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Position History",
    description: "Position History",
    icon: "📜",
    href: "/hr/hub/position-history",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Survey",
    description: "Survey",
    icon: "📊",
    href: "/hr/hub/survey",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Survey Response",
    description: "Survey Response",
    icon: "💬",
    href: "/hr/hub/survey-response",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Development Plan",
    description: "Development Plan",
    icon: "📈",
    href: "/hr/hub/development-plan",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Employee Benefit",
    description: "Employee Benefit",
    icon: "🎁",
    href: "/hr/hub/employee-benefit",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Claim Requests",
    description: "Claim Requests",
    icon: "🧾",
    href: "/hr/hub/claim-requests",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Internal Events",
    description: "Internal Events",
    icon: "📅",
    href: "/hr/hub/internal-events",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Onboarding",
    description: "Onboarding",
    icon: "🧑‍🏫",
    href: "/hr/hub/onboarding",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Performance Review",
    description: "Performance Review",
    icon: "⭐",
    href: "/hr/hub/performance-review",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Positions",
    description: "Positions",
    icon: "💼",
    href: "/hr/hub/positions",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Shifts",
    description: "Shifts",
    icon: "⏰",
    href: "/hr/hub/shifts",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Documents",
    description: "Documents",
    icon: "📄",
    href: "/hr/hub/documents",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
  {
    title: "Training Records",
    description: "Training Records",
    icon: "🎓",
    href: "/hr/hub/training-records",
    rolesAllowed: ["hr", "hr-manager", "admin", "super-admin"],
    allRolesAllowed: false,
    color: "#ad1457",
    isActive: true,
    isSubscribed: true,
    isSubModule: true,
    underMaintainance: false,
    otherScenario: true,
    parentModule: "HR Hub",
    packageCategory: "pro",
  },
];
