import { Role } from "@/lib/auth/protected-routes";
import { Package, PackageFeature } from "./types";

const allRoles: Role[] = [
  "user",
  "super-admin",
  "hr",
  "super-admin",
  "employee",
  "hr-manager",
  "org-admin",
  "manager",
  "admin",
];

export const mainDashCards: Package[] = [
  {
    title: "Sales",
    active: true,
    onTrial: true,
    description: "Manage leads and sales operations.",
    icon: "💼",
    href: "/sales",
    rolesAllowed: ["admin", "sales"],
    color: "#FF6B6B",
    category: "module",
    features: [
      {
        name: "CRM",
        description: "Customer Relationship Management",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/sales/crm",
      },
      {
        name: "Sales Management",
        description: "Manage sales lifecycle and pipelines",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/sales/sales-management",
      },
    ],
  },
  {
    title: "POS",
    onTrial: true,
    active: true,
    description: "Point of Sale solutions for various sectors.",
    icon: "🛒",
    href: "/pos",
    rolesAllowed: ["admin", "cashier"],
    color: "#FFA94D",
    category: "module",
    features: [
      {
        name: "Entertainment & Hospitality POS",
        description: "POS for entertainment and hospitality",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/pos/entertainment-hospitality-pos",
      },
      {
        name: "Retail Sector POS",
        description: "POS for retail businesses",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/pos/shopes",
      },
      {
        name: "Transportation & Travel POS",
        description: "POS for transport and travel",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/pos/transportation-travel-pos",
      },
      {
        name: "Wholesale & Distribution POS",
        description: "POS for wholesale and distribution",
        plan: "premium",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/pos/wholesale-distribution-pos",
      },
      {
        name: "Service Industry POS",
        description: "POS for service industries",
        plan: "premium",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/pos/service-industry-pos",
      },
      {
        name: "Pharmaceuticals",
        description: "POS for pharmaceutical sector",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/pos/pharmaceuticals",
      },
      {
        name: "Food & Beverage POS",
        description: "POS for food and beverage businesses",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/pos/shopes",
      },
    ],
  },
  {
    title: "Projects",
    active: true,
    onTrial: true,
    description: "Project planning and tracking tools.",
    icon: "📊",
    href: "/projects",
    rolesAllowed: ["admin", "pm"],
    color: "#4DABF7",
    category: "module",
    features: [
      {
        name: "Project Management",
        description: "Manage and track project progress",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/projects/project-management",
      },
      {
        name: "Timesheet Management",
        description: "Track time spent on tasks and projects",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/projects/timesheet-management",
      },
    ],
  },
  {
    title: "Assets",
    onTrial: true,
    description: "Track and manage company assets.",
    active: true,
    icon: "🏢",
    href: "/assets",
    rolesAllowed: ["admin", "asset-manager"],
    color: "#69DB7C",
    category: "module",
    features: [
      {
        name: "Fixed Asset Management",
        description: "Manage fixed assets lifecycle",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/assets/fixed-asset-management",
      },
      {
        name: "Fleet Management",
        description: "Track and maintain company vehicles",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/assets/fleet-management",
      },
      {
        name: "Maintenance Management",
        description: "Schedule and track asset maintenance",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/assets/maintenance-management",
      },
    ],
  },
  {
    title: "Self Service",
    active: true,
    onTrial: true,
    description: "Employee portal for internal requests.",
    icon: "🧑‍💼",
    href: "/employee-portal",
    rolesAllowed: ["employee", "admin", "super-admin", "manager"],
    color: "#B197FC",
    category: "module",
    features: [
      {
        name: "Internal Material Request",
        description: "Request internal materials",
        plan: "free",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/employee-portal/internal-material-request",
      },
      {
        name: "Maintenance Request",
        description: "Report maintenance issues",
        plan: "free",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/employee-portal/maintenance-request",
      },
      {
        name: "Purchase Request (PR)",
        description: "Request to purchase items or services",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/employee-portal/purchase-request-pr",
      },
      {
        name: "Expense Reimbursement Request",
        description: "Claim reimbursement for expenses",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/employee-portal/expense-reimbursement-request",
      },
      {
        name: "Leave Request",
        description: "Apply and manage leave",
        plan: "free",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/employee-portal/leaves",
      },
    ],
  },
  {
    title: "Website",
    active: true,
    onTrial: true,
    description: "Website builder and CMS tools.",
    icon: "🌐",
    href: "/website",
    rolesAllowed: ["admin", "editor"],
    color: "#FF8787",
    category: "module",
    features: [
      {
        name: "CMS",
        description: "Manage website content",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/website/cms",
      },
    ],
  },
  {
    title: "SCM",
    active: true,
    onTrial: true,
    description: "Supply chain management tools.",
    icon: "🔗",
    href: "/scm",
    rolesAllowed: ["admin", "supply"],
    color: "#F783AC",
    category: "module",
    features: [
      {
        name: "Inventory Management",
        description: "Track inventory levels and movement",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/scm/inventory",
      },
      {
        name: "Manufacturing",
        description: "Manage production processes",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/scm/manufacturing",
      },
      {
        name: "Procurement",
        description: "Manage purchasing and suppliers",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/scm/procurement",
      },
      {
        name: "Product Management",
        description: "Organize and define product catalog",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/scm/product",
      },
      {
        name: "Cost Accounting Management",
        description: "Analyze and control costs",
        plan: "premium",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/scm/cost",
      },
    ],
  },
  {
    title: "Finance",
    active: true,
    onTrial: true,
    description: "Accounting and financial operations.",
    icon: "💰",
    href: "/finance",
    rolesAllowed: ["admin", "accountant"],
    color: "#63E6BE",
    category: "module",
    features: [
      {
        name: "General Ledger (GL)",
        description: "Track financial transactions",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/finance/general-ledger-gl",
      },
      {
        name: "Accounts Payable (AP)",
        description: "Track outgoing payments",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/finance/accounts-payable-ap",
      },
      {
        name: "Accounts Receivable (AR)",
        description: "Track incoming payments",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/finance/accounts-receivable-ar",
      },
      {
        name: "Bank & Cash Management",
        description: "Manage bank accounts and cash flow",
        plan: "premium",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/finance/bank-cash-management",
      },
      {
        name: "Budgeting",
        description: "Plan and control budgets",
        plan: "premium",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/finance/budgeting",
      },
    ],
  },
  {
    title: "HR",
    active: true,
    onTrial: true,
    description: "Human Resources management tools.",
    icon: "🧑‍🤝‍🧑",
    href: "/hr/hub",
    rolesAllowed: ["admin", "hr"],
    color: "#FFD43B",
    category: "module",
    features: [
      {
        name: "Employee Management",
        description: "Manage employee records and data",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/hr/employees",
      },
      {
        name: "Recruitment & Onboarding",
        description: "Hire and onboard new employees",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/hr/recruitment",
      },
      {
        name: "Payroll",
        description: "Automate employee salary processing",
        plan: "premium",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/hr/payroll",
      },
      {
        name: "Attendance & Timesheets",
        description: "Track attendance and time logs",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/hr/attendance",
      },
      {
        name: "Performance Management",
        description: "Manage employee evaluations",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/hr/performance",
      },

      {
        name: "Training & Development",
        description: "Plan and track employee training",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/hr/training",
      },
    ],
  },
  // {
  //   title: "General Settings",
  //   active: true,
  //   onTrial: true,
  //   description: "General settings for the system.",
  //   icon: "🛠️",
  //   href: "/settings",
  //   rolesAllowed: ["admin", "super-admin"],
  //   color: "#FFD43B",
  //   category: "module",
  //   general: true,
  // },
  {
    title: "CampusHub",
    active: true,
    onTrial: true,
    description:
      "Manage student, academic, attendance, finance, and self-service portals.",
    icon: "🎓",
    href: "/education",
    rolesAllowed: ["admin", "super-admin", "hr", "manager", "employee"],
    color: "#6C63FF",
    category: "module",
    features: [
      {
        name: "Student Information Management (SIM)",
        description:
          "Centralized system for managing all student-related data across their lifecycle",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/education/sim",
      },
      {
        name: "Learning Management System (LMS)",
        description:
          "Platform for delivering, managing, and tracking learning content",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/education/lms",
      },
      {
        name: "Academic Management",
        description:
          "Course catalog, timetable, syllabus mapping, exam scheduling, grading, transcript generation",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/education/academic",
      },
      {
        name: "Attendance Management",
        description:
          "Daily/period attendance, absence approvals, alerts, integration with timetable",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/education/attendance",
      },
      {
        name: "Fee & Finance Management",
        description:
          "Tuition structure, invoicing, scholarships/discounts, fee collection",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/education/finance",
      },
      {
        name: "Self-service Portals",
        description:
          "Student, parent, and teacher portals for accessing grades, schedules, fees, and messages",
        plan: "starter",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/education/self-service",
      },
    ],
  },
  {
    title: "AI",
    active: true,
    onTrial: true,
    description: "AI-powered tools for business optimization.",
    icon: "🧠",
    href: "/ai",
    rolesAllowed: ["admin", "analyst"],
    color: "#A2C3F2",
    category: "module",
    features: [
      {
        name: "Data Analysis & Forecasting",
        description: "Analyze data and predict future trends",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/ai/data-analysis-forecasting",
      },
      {
        name: "Automation of Routine Tasks",
        description: "Automate repetitive tasks and workflows",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/ai/automation-of-routine-tasks",
      },
      {
        name: "Intelligent Recommendations",
        description: "Provide smart recommendations based on user behavior",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/ai/intelligent-recommendations",
      },
      {
        name: "Conversational Assistance",
        description: "Engage users with a conversational AI assistant",
        plan: "pro",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/ai/conversational-assistance",
      },
      {
        name: "Anomaly & Risk Detection",
        description: "Detect unusual patterns and potential risks",
        plan: "premium",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/ai/anomaly-risk-detection",
      },
      {
        name: "Decision Support",
        description: "Assist with data-driven decision making",
        plan: "premium",
        subscribed: true,
        active: true,
        underMaintainance: false,
        link: "/ai/decision-support",
      },
    ],
  },
];
