import { Hub } from "./types";
export const modulabs: Hub[] = [
  {
    title: "Self Service",
    pageLink: "/self-service",
    icon: "🧑‍💻",
    order: 50,
    ariaLabel: "Employee portal for internal requests.",
    code: "HUB_SELFSERVICE",
    modules: [
      {
        title: "Personal",
        pageLink: "/self-service/personal-info",
        icon: "🆔",
        order: 10,
        ariaLabel: "View and update personal employee information",
        code: "MOD_SS_PERSONAL",
        entities: [
          {
            title: "Personal Info",
            pageLink: "/self-service/profile",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "👤",
            description:
              "View and update your personal and contact information.",
            category: "Profile",
            order: 10,
            ariaLabel: "Manage personal information",
            disabled: false,
            code: "ENT_SS_PERSONAL",
          },
          {
            title: "Benefits",
            pageLink: "/self-service/benefits",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "🤲",
            description: "View your current benefits enrollment and options.",
            category: "HR",
            order: 20,
            ariaLabel: "View and manage benefits",
            disabled: false,
            code: "ENT_SS_BENEFITS",
          },
          {
            title: "Documents",
            pageLink: "/self-service/documents",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "📄",
            description: "Access official HR and company documents.",
            category: "HR",
            order: 30,
            ariaLabel: "Access personal documents",
            disabled: false,
            code: "ENT_SS_DOCS",
          },
        ],
      },
      {
        title: "Recruitment & Exit",
        pageLink: "/self-service/jobs",
        icon: "🔍",
        order: 30,
        ariaLabel: "View internal job openings and manage exit procedures",
        code: "MOD_SS_RECRUIT",
        entities: [
          {
            title: "Attendance",
            pageLink: "/self-service/attendance",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "🗓️",
            description: "Record and view your daily attendance logs.",
            category: "Time",
            order: 10,
            ariaLabel: "View attendance records",
            disabled: false,
            code: "ENT_SS_ATTEND",
          },
          {
            title: "Leave Requests",
            pageLink: "/self-service/leaves",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "📅",
            description: "Apply and manage vacation or sick leave requests.",
            category: "Time",
            order: 20,
            ariaLabel: "Submit and track leave requests",
            disabled: false,
            code: "ENT_SS_LEAVE",
          },
          {
            title: "Internal Jobs",
            pageLink: "/self-service/jobs",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "💼",
            description: "Browse and apply for internal job opportunities.",
            category: "Career",
            order: 10,
            ariaLabel: "View open jobs",
            disabled: false,
            code: "ENT_SS_JOBS",
          },
          {
            title: "Job Requisitions",
            pageLink: "/self-service/job-req",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "✍️",
            description: "View status of submitted job requisition requests.",
            category: "HR",
            order: 20,
            ariaLabel: "Track job requisitions",
            disabled: false,
            code: "ENT_SS_JOBREQ",
          },
          {
            title: "Exits",
            pageLink: "/self-service/exits",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "🚪",
            description: "Initiate or track employee offboarding process.",
            category: "HR",
            order: 30,
            ariaLabel: "Manage exit procedures",
            disabled: false,
            code: "ENT_SS_EXITS",
          },
        ],
      },
      {
        title: "Performance & Finance",
        pageLink: "/self-service/payslips",
        icon: "📊",
        order: 40,
        ariaLabel: "Access payslips and performance info",
        code: "MOD_SS_PERF_FIN",
        entities: [
          {
            title: "Payslips",
            pageLink: "/self-service/payslips",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "💰",
            description: "Access and download your historical pay statements.",
            category: "Finance",
            order: 10,
            ariaLabel: "View payslips",
            disabled: false,
            code: "ENT_SS_PAYSLIPS",
          },
          {
            title: "Appraisal Evaluation",
            pageLink: "/self-service/appraisal-evaluation",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "📈",
            description: "View your performance appraisal results.",
            category: "Performance",
            order: 20,
            ariaLabel: "View appraisal evaluation",
            disabled: false,
            code: "ENT_SS_APPRAISAL",
          },
          {
            title: "Training & Performance",
            pageLink: "/self-service/training-performance",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "🎓",
            description:
              "View your training history and performance objectives.",
            category: "Performance",
            order: 30,
            ariaLabel: "Access training and performance goals",
            disabled: false,
            code: "ENT_SS_TRAIN_PERF",
          },
          {
            title: "Survey",
            pageLink: "/self-service/survey",
            allowedPermissions: ["employee", "admin", "super-admin", "manager"],
            icon: "📋",
            description: "Participate in or view results of internal surveys.",
            category: "HR",
            order: 40,
            ariaLabel: "Access employee surveys",
            disabled: false,
            code: "ENT_SS_SURVEY",
          },
        ],
      },
    ],
  },
  {
    title: "HR",
    pageLink: "/hr/hub",
    icon: "👥",
    order: 90,
    ariaLabel: "Human Resources management tools.",
    code: "HUB_HR",
    modules: [
      {
        title: "Employees",
        pageLink: "/hr/employees",
        icon: "👔",
        order: 10,
        ariaLabel: "Manage employee records and life cycle",
        code: "MOD_HR_EMP",
        entities: [
          {
            title: "Employee Directory",
            pageLink: "/hr/employees/employees",
            allowedPermissions: ["admin", "hr"],
            icon: "👥",
            description: "Master list of all employee records and data.",
            category: "Personnel",
            order: 10,
            ariaLabel: "View employee directory",
            disabled: false,
            code: "ENT_HR_EMP_DIR",
          },
          {
            title: "Contracts",
            pageLink: "/hr/employees/contracts",
            allowedPermissions: ["admin", "hr"],
            icon: "📜",
            description: "Manage employee contracts and terms.",
            category: "Personnel",
            order: 20,
            ariaLabel: "Manage employee contracts",
            disabled: false,
            code: "ENT_HR_EMP_CONTRACTS",
          },
          {
            title: "Documents",
            pageLink: "/hr/employees/documents",
            allowedPermissions: ["admin", "hr"],
            icon: "📄",
            description: "Manage employee-related documents.",
            category: "Personnel",
            order: 30,
            ariaLabel: "Manage employee documents",
            disabled: false,
            code: "ENT_HR_EMP_DOCS",
          },
          {
            title: "Dashboard",
            pageLink: "/hr/employees/dashboard",
            allowedPermissions: ["admin", "hr"],
            icon: "🥧",
            description: "Overview of key employee metrics.",
            category: "Reporting",
            order: 40,
            ariaLabel: "View employee dashboard",
            disabled: false,
            code: "ENT_HR_EMP_DASH",
          },
          {
            title: "Offboarding Request",
            pageLink: "/hr/employees/offboarding-request",
            allowedPermissions: ["admin", "hr"],
            icon: "🚪",
            description: "Manage requests for employee offboarding.",
            category: "Lifecycle",
            order: 50,
            ariaLabel: "Manage offboarding requests",
            disabled: false,
            code: "ENT_HR_OFFBOARD_REQ",
          },
          {
            title: "Settings",
            pageLink: "/hr/employees/settings",
            allowedPermissions: ["admin", "hr"],
            icon: "⚙️",
            description: "Configure employee module settings.",
            category: "settings",
            order: 60,
            ariaLabel: "Configure employee settings",
            disabled: false,
            code: "ENT_HR_EMP_SETTINGS",
          },
        ],
      },
      {
        title: "Recruitment",
        pageLink: "/hr/recruitment",
        icon: "🔍",
        order: 20,
        ariaLabel: "Manage job requisitions and candidate tracking",
        code: "MOD_HR_RECRUIT",
        entities: [
          {
            title: "Job Requisition",
            pageLink: "/hr/recruitment/job-requisition",
            allowedPermissions: ["admin", "hr"],
            icon: "✍️",
            description: "Manage requests for new open positions.",
            category: "Hiring",
            order: 10,
            ariaLabel: "Manage job requisitions",
            disabled: false,
            code: "ENT_HR_JOB_REQ",
          },
          {
            title: "Candidates",
            pageLink: "/hr/recruitment/candidate",
            allowedPermissions: ["admin", "hr"],
            icon: "👤",
            description: "Manage the pool of job candidates.",
            category: "Hiring",
            order: 20,
            ariaLabel: "Manage candidate pool",
            disabled: false,
            code: "ENT_HR_CANDIDATE",
          },
          {
            title: "Applications",
            pageLink: "/hr/recruitment/application",
            allowedPermissions: ["admin", "hr"],
            icon: "✉️",
            description: "View and manage job applications.",
            category: "Hiring",
            order: 30,
            ariaLabel: "Manage job applications",
            disabled: false,
            code: "ENT_HR_APPLY",
          },
          {
            title: "Offers",
            pageLink: "/hr/recruitment/offer",
            allowedPermissions: ["admin", "hr"],
            icon: "🏅",
            description: "Generate and track offer letters.",
            category: "Hiring",
            order: 40,
            ariaLabel: "Manage job offers",
            disabled: false,
            code: "ENT_HR_OFFER",
          },
          {
            title: "Onboarding Plan",
            pageLink: "/hr/recruitment/onboarding-plan",
            allowedPermissions: ["admin", "hr"],
            icon: "✅",
            description: "Set up and manage employee onboarding plans.",
            category: "Hiring",
            order: 50,
            ariaLabel: "Manage onboarding plans",
            disabled: false,
            code: "ENT_HR_ONBOARD_PLAN",
          },
          {
            title: "Pipeline Stage",
            pageLink: "/hr/recruitment/pipeline-stage",
            allowedPermissions: ["admin", "hr"],
            icon: "🛣️",
            description: "Define and manage recruitment pipeline stages.",
            category: "settings",
            order: 60,
            ariaLabel: "Manage pipeline stages",
            disabled: false,
            code: "ENT_HR_PIPE_STAGE",
          },
        ],
      },
      {
        title: "Leave Management",
        pageLink: "/hr/leave",
        icon: "📅",
        order: 30,
        ariaLabel: "Manage time-off requests and balances",
        code: "MOD_HR_LEAVE",
        entities: [
          {
            title: "Leave Request",
            pageLink: "/hr/leave/leave-request",
            allowedPermissions: ["admin", "hr"],
            icon: "➖📅",
            description: "Review and process submitted leave requests.",
            category: "Transactions",
            order: 10,
            ariaLabel: "Process leave requests",
            disabled: false,
            code: "ENT_HR_LEAVE_REQ",
          },
          {
            title: "Leave Balance",
            pageLink: "/hr/leave/leave-balance",
            allowedPermissions: ["admin", "hr"],
            icon: "⚖️",
            description: "Track and adjust employee leave balances.",
            category: "Transactions",
            order: 20,
            ariaLabel: "Manage leave balances",
            disabled: false,
            code: "ENT_HR_LEAVE_BAL",
          },
          {
            title: "Leave Types",
            pageLink: "/hr/leave/settings/leave-type",
            allowedPermissions: ["admin", "hr"],
            icon: "📋",
            description:
              "Define different types of leaves (e.g., Sick, Annual).",
            category: "settings",
            order: 30,
            ariaLabel: "Manage leave types",
            disabled: false,
            code: "ENT_HR_LEAVE_TYPES",
          },
          {
            title: "Holidays",
            pageLink: "/hr/leave/settings/holiday",
            allowedPermissions: ["admin", "hr"],
            icon: "🏖️",
            description: "Manage company holidays.",
            category: "settings",
            order: 40,
            ariaLabel: "Manage company holidays",
            disabled: false,
            code: "ENT_HR_LEAVE_HOLIDAYS",
          },
          {
            title: "Work Schedule",
            pageLink: "/hr/leave/settings/work-schedule",
            allowedPermissions: ["admin", "hr"],
            icon: "🕔",
            description: "Define standard work schedules.",
            category: "settings",
            order: 50,
            ariaLabel: "Manage work schedules",
            disabled: false,
            code: "ENT_HR_LEAVE_SCHED",
          },
          {
            title: "Leave Encashment",
            pageLink: "/hr/leave/leave-encashment",
            allowedPermissions: ["admin", "hr"],
            icon: "💸",
            description: "Process payments for unused leave days.",
            category: "Compensation",
            order: 60,
            ariaLabel: "Process leave encashment",
            disabled: false,
            code: "ENT_HR_LEAVE_CASH",
          },
        ],
      },
      {
        title: "Attendance",
        pageLink: "/hr/attendance",
        icon: "⏰",
        order: 40,
        ariaLabel: "Track time logs, shifts, and attendance rules",
        code: "MOD_HR_ATTEND",
        entities: [
          {
            title: "Attendance Logs",
            pageLink: "/hr/attendance/attendance",
            allowedPermissions: ["admin", "hr"],
            icon: "🗓️",
            description: "View and manage employee attendance records.",
            category: "Time Tracking",
            order: 10,
            ariaLabel: "Manage attendance logs",
            disabled: false,
            code: "ENT_HR_ATTEND_LOGS",
          },
          {
            title: "Shifts",
            pageLink: "/hr/attendance/shifts",
            allowedPermissions: ["admin", "hr"],
            icon: "🔁",
            description: "Define and assign work shifts to employees.",
            category: "settings",
            order: 20,
            ariaLabel: "Manage work shifts",
            disabled: false,
            code: "ENT_HR_ATTEND_SHIFTS",
          },
          {
            title: "Attendance Rules",
            pageLink: "/hr/attendance/attendance-rules",
            allowedPermissions: ["admin", "hr"],
            icon: "🔨",
            description: "Configure rules for late check-ins and overtime.",
            category: "settings",
            order: 30,
            ariaLabel: "Manage attendance rules",
            disabled: false,
            code: "ENT_HR_ATTEND_RULES",
          },
          {
            title: "Overtime",
            pageLink: "/hr/attendance/overtime",
            allowedPermissions: ["admin", "hr"],
            icon: "➕",
            description: "Review and approve employee overtime records.",
            category: "Time Tracking",
            order: 40,
            ariaLabel: "Manage overtime records",
            disabled: false,
            code: "ENT_HR_ATTEND_OT",
          },
          {
            title: "Work Schedule",
            pageLink: "/hr/attendance/work-schedule",
            allowedPermissions: ["admin", "hr"],
            icon: "🕔",
            description:
              "Define employee work schedules for attendance tracking.",
            category: "settings",
            order: 50,
            ariaLabel: "Manage attendance work schedule",
            disabled: false,
            code: "ENT_HR_ATTEND_SCHED",
          },
        ],
      },
      {
        title: "Payroll",
        pageLink: "/hr/payroll",
        icon: "💸",
        order: 50,
        ariaLabel: "Manage salary processing and pay components",
        code: "MOD_HR_PAYROLL",
        entities: [
          {
            title: "Payslips",
            pageLink: "/hr/payroll/payslips",
            allowedPermissions: ["admin", "hr"],
            icon: "🧾",
            description: "Generate and manage employee pay statements.",
            category: "Transactions",
            order: 10,
            ariaLabel: "Manage payslips",
            disabled: false,
            code: "ENT_HR_PAY_SLIPS",
          },
          {
            title: "Generate Single Payslip",
            pageLink: "/hr/payroll/generate-single-payslip",
            allowedPermissions: ["admin", "hr"],
            icon: "📄",
            description: "Generate individual employee pay statements.",
            category: "Transactions",
            order: 20,
            ariaLabel: "Generate a payslip for a single employee",
            disabled: false,
            code: "ENT_HR_SINGLE_PAY_SLIPS",
          },
          {
            title: "Payroll Batches",
            pageLink: "/hr/payroll/payroll-batches",
            allowedPermissions: ["admin", "hr"],
            icon: "📦",
            description: "Group and process payroll for a period.",
            category: "Transactions",
            order: 30,
            ariaLabel: "Manage payroll batches",
            disabled: false,
            code: "ENT_HR_PAY_BATCH",
          },
          {
            title: "Salary Structure",
            pageLink: "/hr/payroll/settings/salary-structure",
            allowedPermissions: ["admin", "hr"],
            icon: "🏗️",
            description: "Define the framework for calculating salaries.",
            category: "settings",
            order: 40,
            ariaLabel: "Manage salary structure",
            disabled: false,
            code: "ENT_HR_PAY_STRUC",
          },
          {
            title: "Salary Structure Rules",
            pageLink: "/hr/payroll/settings/salary-structure-rules",
            allowedPermissions: ["admin", "hr"],
            icon: "⚙️",
            description:
              "Defines how an employee's total salary is calculated.",
            category: "settings",
            order: 50,
            ariaLabel: "Manage salary structure rules",
            disabled: false,
            code: "ENT_HR_PAY_STRUC_RULES",
          },
          {
            title: "Salary Rules",
            pageLink: "/hr/payroll/settings/salary-rules",
            allowedPermissions: ["admin", "hr"],
            icon: "📐",
            description: "Define calculation rules for salary components.",
            category: "settings",
            order: 60,
            ariaLabel: "Manage salary rules",
            disabled: false,
            code: "ENT_HR_PAY_RULES",
          },
          {
            title: "Tax Brackets",
            pageLink: "/hr/payroll/tax-bracket",
            allowedPermissions: ["admin", "hr"],
            icon: "📊",
            description: "Manage tax brackets and compliance rates.",
            category: "Compliance",
            order: 70,
            ariaLabel: "Manage tax brackets",
            disabled: false,
            code: "ENT_HR_PAY_TAX",
          },
          {
            title: "Payslip Inputs",
            pageLink: "/hr/payroll/payslip-inputs",
            allowedPermissions: ["admin", "hr"],
            icon: "⌨️",
            description:
              "Define temporary, employee-specific data used to influence salary calculations.",
            category: "settings",
            order: 80,
            ariaLabel: "Manage payslip inputs",
            disabled: false,
            code: "ENT_HR_PAY_INPUTS",
          },
          {
            title: "Bank Accounts",
            pageLink: "/hr/payroll/bank-accounts",
            allowedPermissions: ["admin", "hr"],
            icon: "🏦",
            description: "Manage employee bank account information.",
            category: "settings",
            order: 90,
            ariaLabel: "Manage employee bank accounts",
            disabled: false,
            code: "ENT_HR_BANK_ACCOUNTS",
          },
          {
            title: "Work Entries",
            pageLink: "/hr/payroll/work-entries",
            allowedPermissions: ["admin", "hr"],
            icon: "⏱️",
            description:
              "View employee records of worked and non-worked time for payroll periods.",
            category: "Time Tracking",
            order: 100,
            ariaLabel: "View work entries",
            disabled: false,
            code: "ENT_HR_WORK_ENTRIES",
          },
          {
            title: "Salary Rule Categories",
            pageLink: "/hr/payroll/settings/salary-rule-categories",
            allowedPermissions: ["admin", "hr"],
            icon: "📑",
            description:
              "Organize salary rules based on their type or purpose.",
            category: "settings",
            order: 110,
            ariaLabel: "Manage salary rule categories",
            disabled: false,
            code: "ENT_HR_SAL_RULE_CAT",
          },
          {
            title: "Payroll Periods",
            pageLink: "/hr/payroll/settings/periods",
            allowedPermissions: ["admin", "hr"],
            icon: "📅",
            description: "Define the company's payroll cycles.",
            category: "settings",
            order: 120,
            ariaLabel: "Manage payroll periods",
            disabled: false,
            code: "ENT_HR_PAY_PERIOD",
          },
          {
            title: "Pension Policy",
            pageLink: "/hr/payroll/pension-policy",
            allowedPermissions: ["admin", "hr"],
            icon: "👵",
            description: "Manage company pension contribution rules.",
            category: "Compliance",
            order: 130,
            ariaLabel: "Manage pension policy",
            disabled: false,
            code: "ENT_HR_PENSION_POLICY",
          },
          {
            title: "Reports",
            pageLink: "/hr/payroll/reports",
            allowedPermissions: ["admin", "hr"],
            icon: "📈",
            description: "Generate comprehensive payroll reports.",
            category: "Reporting",
            order: 140,
            ariaLabel: "View payroll reports",
            disabled: false,
            code: "ENT_HR_PAY_REPORT",
          },
        ],
      },
      {
        title: "Performance",
        pageLink: "/hr/performance",
        icon: "📊",
        order: 60,
        ariaLabel: "Manage employee evaluations and goals",
        code: "MOD_HR_PERF",
        entities: [
          {
            title: "Performance Review",
            pageLink: "/hr/performance/performance-review",
            allowedPermissions: ["admin", "hr"],
            icon: "💬",
            description:
              "Conduct and manage formal employee performance reviews.",
            category: "Evaluation",
            order: 10,
            ariaLabel: "Manage performance reviews",
            disabled: false,
            code: "ENT_HR_PERF_REVIEW",
          },
          {
            title: "Appraisal Evaluation",
            pageLink: "/hr/performance/appraisalevaluation",
            allowedPermissions: ["admin", "hr"],
            icon: "⭐",
            description: "View and finalize appraisal scores and evaluations.",
            category: "Evaluation",
            order: 20,
            ariaLabel: "Manage appraisal evaluations",
            disabled: false,
            code: "ENT_HR_PERF_APPRAISAL",
          },
          {
            title: "Goals",
            pageLink: "/hr/performance/goal",
            allowedPermissions: ["admin", "hr"],
            icon: "🎯",
            description:
              "Define, track, and manage employee performance goals.",
            category: "Goals",
            order: 30,
            ariaLabel: "Manage employee goals",
            disabled: false,
            code: "ENT_HR_PERF_GOALS",
          },
          {
            title: "KPIs",
            pageLink: "/hr/performance/kpi",
            allowedPermissions: ["admin", "hr"],
            icon: " speedo.svg",
            description: "Manage Key Performance Indicators for evaluation.",
            category: "Goals",
            order: 40,
            ariaLabel: "Manage KPIs",
            disabled: false,
            code: "ENT_HR_PERF_KPI",
          },
          {
            title: "Templates",
            pageLink: "/hr/performance/template",
            allowedPermissions: ["admin", "hr"],
            icon: " stamp.svg",
            description: "Create and manage performance review templates.",
            category: "settings",
            order: 50,
            ariaLabel: "Manage performance templates",
            disabled: false,
            code: "ENT_HR_PERF_TEMPL",
          },
          {
            title: "Incidents",
            pageLink: "/hr/performance/incident",
            allowedPermissions: ["admin", "hr"],
            icon: "⚠️",
            description: "Record and track performance or conduct incidents.",
            category: "Discipline",
            order: 60,
            ariaLabel: "Manage performance incidents",
            disabled: false,
            code: "ENT_HR_PERF_INCIDENT",
          },
        ],
      },
      {
        title: "Training",
        pageLink: "/hr/training",
        icon: "🎓",
        order: 70,
        ariaLabel: "Plan and track employee training and development",
        code: "MOD_HR_TRAINING",
        entities: [
          {
            title: "Training Record",
            pageLink: "/hr/training/training-record",
            allowedPermissions: ["admin", "hr"],
            icon: " numbered_list.svg",
            description:
              "Maintain a history of all completed employee training.",
            category: "Records",
            order: 10,
            ariaLabel: "Manage training records",
            disabled: false,
            code: "ENT_HR_TRAIN_REC",
          },
          {
            title: "Training Request",
            pageLink: "/hr/training/training-request",
            allowedPermissions: ["admin", "hr"],
            icon: "📥",
            description: "Review and approve requests for new training.",
            category: "Requests",
            order: 20,
            ariaLabel: "Manage training requests",
            disabled: false,
            code: "ENT_HR_TRAIN_REQ",
          },
          {
            title: "Training Session",
            pageLink: "/hr/training/training-session",
            allowedPermissions: ["admin", "hr"],
            icon: "👥",
            description: "Schedule and manage individual training sessions.",
            category: "Delivery",
            order: 30,
            ariaLabel: "Manage training sessions",
            disabled: false,
            code: "ENT_HR_TRAIN_SESS",
          },
          {
            title: "Training Attendance",
            pageLink: "/hr/training/training-attendance",
            allowedPermissions: ["admin", "hr"],
            icon: "🗓️",
            description: "Record and track attendance for training sessions.",
            category: "Delivery",
            order: 40,
            ariaLabel: "Manage training attendance",
            disabled: false,
            code: "ENT_HR_TRAIN_ATTEND",
          },
          {
            title: "TNA Survey",
            pageLink: "/hr/training/tna-survey",
            allowedPermissions: ["admin", "hr"],
            icon: "📋",
            description: "Conduct Training Needs Analysis surveys.",
            category: "Analysis",
            order: 50,
            ariaLabel: "Manage TNA surveys",
            disabled: false,
            code: "ENT_HR_TRAIN_TNA",
          },
          {
            title: "Trainer",
            pageLink: "/hr/training/trainer",
            allowedPermissions: ["admin", "hr"],
            icon: "👩‍🏫",
            description: "Manage the list of internal and external trainers.",
            category: "settings",
            order: 60,
            ariaLabel: "Manage trainers",
            disabled: false,
            code: "ENT_HR_TRAIN_TRAINER",
          },
        ],
      },
      {
        title: "Compliance",
        pageLink: "/hr/compliance",
        icon: "🛡️",
        order: 80,
        ariaLabel: "Manage regulatory compliance and safety",
        code: "MOD_HR_COMP",
        entities: [
          {
            title: "Compliance Requirements",
            pageLink: "/hr/compliance/compliance-requirement",
            allowedPermissions: ["admin", "hr"],
            icon: " checklist.svg",
            description: "Define and manage required compliance items.",
            category: "Audit",
            order: 10,
            ariaLabel: "Manage compliance requirements",
            disabled: false,
            code: "ENT_HR_COMP_REQ",
          },
          {
            title: "Compliance Audits",
            pageLink: "/hr/compliance/compliance-audit",
            allowedPermissions: ["admin", "hr"],
            icon: "🔍",
            description: "Schedule and track internal compliance audits.",
            category: "Audit",
            order: 20,
            ariaLabel: "Manage compliance audits",
            disabled: false,
            code: "ENT_HR_COMP_AUDIT",
          },
          {
            title: "Compliance Task",
            pageLink: "/hr/compliance/compliance-task",
            allowedPermissions: ["admin", "hr"],
            icon: "📋",
            description: "Manage tasks related to fulfilling compliance.",
            category: "Audit",
            order: 30,
            ariaLabel: "Manage compliance tasks",
            disabled: false,
            code: "ENT_HR_COMP_TASK",
          },
        ],
      },
    ],
  },
  {
    title: "General Settings",
    pageLink: "/settings",
    icon: "⚙️",
    order: 100,
    ariaLabel: "General settings for the system.",
    code: "HUB_SETTINGS",
    modules: [
      {
        title: "User & Roles",
        pageLink: "/settings/users",
        icon: "👥⚙️",
        order: 10,
        ariaLabel: "Manage users, roles, and permissions",
        code: "MOD_SET_USERS",
        entities: [
          {
            title: "Users",
            pageLink: "/settings/users/users",
            allowedPermissions: ["admin", "super-admin"],
            icon: "👤",
            description: "Manage all system user accounts.",
            category: "Administration",
            order: 10,
            ariaLabel: "Manage system users",
            disabled: false,
            code: "ENT_SET_USERS",
          },
          {
            title: "Roles",
            pageLink: "/settings/users/roles",
            allowedPermissions: ["admin", "super-admin"],
            icon: "🏷️",
            description: "Define and manage user roles.",
            category: "Security",
            order: 20,
            ariaLabel: "Manage user roles",
            disabled: false,
            code: "ENT_SET_ROLES",
          },
          {
            title: "Permissions",
            pageLink: "/settings/users/permissions",
            allowedPermissions: ["admin", "super-admin"],
            icon: "🔒",
            description: "Manage individual system permissions.",
            category: "Security",
            order: 30,
            ariaLabel: "Manage system permissions",
            disabled: false,
            code: "ENT_SET_PERMS",
          },
          {
            title: "Role Permission Map",
            pageLink: "/settings/users/role-permission",
            allowedPermissions: ["admin", "super-admin"],
            icon: "🔑",
            description: "Assign permissions to specific roles.",
            category: "Security",
            order: 40,
            ariaLabel: "Map roles to permissions",
            disabled: false,
            code: "ENT_SET_ROLE_PERM",
          },
          {
            title: "User Role Assignment",
            pageLink: "/settings/users/user-role",
            allowedPermissions: ["admin", "super-admin"],
            icon: "👤✅",
            description: "Assign roles to individual users.",
            category: "Security",
            order: 50,
            ariaLabel: "Assign roles to users",
            disabled: false,
            code: "ENT_SET_USER_ROLE",
          },
          {
            title: "Node Assignment",
            pageLink: "/settings/users/node-assignment",
            allowedPermissions: ["admin", "super-admin"],
            icon: " signs.svg",
            description: "Assign users to specific organizational nodes.",
            category: "Administration",
            order: 60,
            ariaLabel: "Manage user node assignments",
            disabled: false,
            code: "ENT_SET_NODE_ASSIGN",
          },
        ],
      },
      {
        title: "Approvals",
        pageLink: "/settings/approval",
        icon: "👍",
        order: 20,
        ariaLabel: "Configure approval workflows and policies",
        code: "MOD_SET_APPROVAL",
        entities: [
          {
            title: "Approval Policy",
            pageLink: "/settings/approval/approval-policy",
            allowedPermissions: ["admin", "super-admin"],
            icon: "📜",
            description:
              "Define rules and steps for document/request approval.",
            category: "Workflow",
            order: 10,
            ariaLabel: "Manage approval policies",
            disabled: false,
            code: "ENT_SET_APP_POLICY",
          },
          {
            title: "Approval Group",
            pageLink: "/settings/approval/approval-group",
            allowedPermissions: ["admin", "super-admin"],
            icon: "👥",
            description:
              "Define groups of users authorized for specific approvals.",
            category: "Workflow",
            order: 20,
            ariaLabel: "Manage approval groups",
            disabled: false,
            code: "ENT_SET_APP_GROUP",
          },
          {
            title: "Delegation",
            pageLink: "/settings/approval/delegation",
            allowedPermissions: ["admin", "super-admin"],
            icon: "🧑‍🤝‍🧑",
            description: "Set up temporary delegation of approval rights.",
            category: "Workflow",
            order: 30,
            ariaLabel: "Manage approval delegation",
            disabled: false,
            code: "ENT_SET_APP_DELEG",
          },
        ],
      },
      {
        title: "Organization",
        pageLink: "/settings/org",
        icon: "🕸️",
        order: 30,
        ariaLabel: "Define the company's organizational structure",
        code: "MOD_SET_ORG",
        entities: [
          {
            title: "Org Structure",
            pageLink: "/settings/org/structure",
            allowedPermissions: ["admin", "super-admin"],
            icon: "🏢",
            description: "Define and manage the organizational hierarchy.",
            category: "Master Data",
            order: 10,
            ariaLabel: "Manage organization structure",
            disabled: false,
            code: "ENT_SET_ORG_STRUC",
          },
          {
            title: "Approval Steps",
            pageLink: "/settings/org/approval-steps",
            allowedPermissions: ["admin", "super-admin"],
            icon: "",
            description:
              "Define standard approval steps specific to organization units.",
            category: "Workflow",
            order: 20,
            ariaLabel: "Manage organizational approval steps",
            disabled: false,
            code: "ENT_SET_ORG_APP_STEP",
          },
          {
            title: "Approval Policy",
            pageLink: "/settings/org/approval-policy",
            allowedPermissions: ["admin", "super-admin"],
            icon: "📜",
            description: "Define policies for organizational approvals.",
            category: "Workflow",
            order: 30,
            ariaLabel: "Manage organizational approval policies",
            disabled: false,
            code: "ENT_SET_ORG_APP_POL",
          },
        ],
      },
      {
        title: "Tutorials",
        pageLink: "/tutorials",
        icon: "📖",
        order: 40,
        ariaLabel: "Access system tutorials and guides.",
        code: "MOD_SET_TUTORIALS",
        entities: [
          {
            title: "Tutorials",
            pageLink: "/tutorials",
            allowedPermissions: ["admin", "super-admin"],
            icon: "▶️",
            description: "Access user and administrator tutorials.",
            category: "Help",
            order: 10,
            ariaLabel: "Access system tutorials",
            disabled: false,
            code: "ENT_SET_TUTORIALS",
          },
        ],
      },
    ],
  },
  {
    title: "Super Admin",
    pageLink: "/super-admin",
    icon: "🦸",
    order: 110,
    ariaLabel: "Tools for system administrators.",
    code: "HUB_SUPER_ADMIN",
    modules: [
      {
        title: "Constants",
        pageLink: "/super-admin/constants",
        icon: "🧩",
        order: 10,
        ariaLabel: "Manage system-wide constant values",
        code: "MOD_SA_CONSTANTS",
        entities: [
          {
            title: "Document Types",
            pageLink: "/super-admin/constants/document-types",
            allowedPermissions: ["super-admin"],
            icon: "📁",
            description: "Manage types of documents used across the system.",
            category: "settings",
            order: 10,
            ariaLabel: "Manage document types",
            disabled: false,
            code: "ENT_SA_DOC_TYPES",
          },
          {
            title: "Permissions",
            pageLink: "/super-admin/constants/permissions",
            allowedPermissions: ["super-admin"],
            icon: "🔒",
            description: "Master list of all definable system permissions.",
            category: "settings",
            order: 20,
            ariaLabel: "Manage master permissions",
            disabled: false,
            code: "ENT_SA_PERMS",
          },
        ],
      },
    ],
  },
];
