import { selfServiceLinks } from "@/components/nav-items/self-service-links";
import { settingsModulabs } from "./settings-modulabs";
import { trainingModulabs } from "./training-modules";

export type Modulab = {
  link: string;
  hub: string;
  module?: string;
  category?: string;
  entity?: string;
  name: string;
  emojie: string;
};
export const modulabs: Modulab[] = [
  ...settingsModulabs,
  ...selfServiceLinks,
  {
    link: "/hr",
    hub: "hr",
    name: "Hr",
    emojie: "🏢",
    category: "navigation",
  },
  {
    link: "/hr/attendance",
    hub: "hr",
    module: "attendance",
    name: "Attendance",
    emojie: "⌚",
    category: "attendance",
  },
  {
    link: "/hr/attendance/attendance",
    hub: "hr",
    module: "attendance",
    entity: "attendance",
    name: "Attendance",
    emojie: "⏰",
    category: "attendance",
  },
  {
    link: "/hr/attendance/attendance-device",
    hub: "hr",
    module: "attendance",
    entity: "attendance-device",
    name: "Attendance Device",
    emojie: "📱",
    category: "settings",
  },
  {
    link: "/hr/attendance/attendance-rule-approver",
    hub: "hr",
    module: "attendance",
    entity: "attendance-rule-approver",
    name: "Attendance Rule Approver",
    emojie: "🧑‍⚖️",
    category: "settings",
  },
  {
    link: "/hr/attendance/attendance-rules",
    hub: "hr",
    module: "attendance",
    entity: "attendance-rules",
    name: "Attendance Rules",
    emojie: "⚖️",
    category: "settings",
  },
  {
    link: "/hr/attendance/attendance/test",
    hub: "hr",
    module: "attendance",
    entity: "test",
    name: "Test",
    emojie: "🧪",
    category: "testing",
  },
  {
    link: "/hr/attendance/method-setup",
    hub: "hr",
    module: "attendance",
    entity: "method-setup",
    name: "Method Setup",
    emojie: "🛠️",
    category: "settings",
  },
  {
    link: "/hr/attendance/overtime",
    hub: "hr",
    module: "attendance",
    entity: "overtime",
    name: "Overtime",
    emojie: "⏳",
    category: "attendance",
  },
  {
    link: "/hr/attendance/work-schedule",
    hub: "hr",
    module: "attendance",
    entity: "work-schedule",
    name: "Work Schedule",
    emojie: "🗓️",
    category: "settings",
  },
  {
    link: "/hr/attendance/work-schedule-slot",
    hub: "hr",
    module: "attendance",
    entity: "work-schedule-slot",
    name: "Work Schedule Slot",
    emojie: "🕒",
    category: "settings",
  },
  {
    link: "/hr/compliance",
    hub: "hr",
    module: "compliance",
    name: "Compliance",
    emojie: "🛡️",
    category: "compliance",
  },
  {
    link: "/hr/compliance/compliance",
    hub: "hr",
    module: "compliance",
    entity: "compliance",
    name: "Compliance",
    emojie: "✔️",
    category: "compliance",
  },
  {
    link: "/hr/compliance/compliance-audit",
    hub: "hr",
    module: "compliance",
    entity: "compliance-audit",
    name: "Compliance Audit",
    emojie: "🔎",
    category: "compliance",
  },
  {
    link: "/hr/compliance/compliance-requirement",
    hub: "hr",
    module: "compliance",
    entity: "compliance-requirement",
    name: "Compliance Requirement",
    emojie: "📜",
    category: "compliance",
  },
  {
    link: "/hr/compliance/compliance-task",
    hub: "hr",
    module: "compliance",
    entity: "compliance-task",
    name: "Compliance Task",
    emojie: "✅",
    category: "compliance",
  },
  {
    link: "/hr/employees",
    hub: "hr",
    module: "employees",
    name: "Employees",
    emojie: "👨‍💼",
    category: "employees",
  },
  {
    link: "/hr/employees/contracts",
    hub: "hr",
    module: "employees",
    entity: "contracts",
    name: "Contracts",
    emojie: "🤝",
    category: "employees",
  },
  ...trainingModulabs,
  {
    link: "/hr/employees/documents",
    hub: "hr",
    module: "employees",
    entity: "documents",
    name: "Documents",
    emojie: "📜",
    category: "employees",
  },
  {
    link: "/hr/employees/employees",
    hub: "hr",
    module: "employees",
    entity: "employees",
    name: "Employees",
    emojie: "👥",
    category: "employees",
  },
  {
    link: "/hr/employees/exit-survey",
    hub: "hr",
    module: "employees",
    entity: "exit-survey",
    name: "Exit Survey",
    emojie: "👋",
    category: "offboarding",
  },
  {
    link: "/hr/employees/exit-survey-response",
    hub: "hr",
    module: "employees",
    entity: "exit-survey-response",
    name: "Exit Survey Response",
    emojie: "💬",
    category: "offboarding",
  },
  {
    link: "/hr/employees/offboarding-question",
    hub: "hr",
    module: "employees",
    entity: "offboarding-question",
    name: "Offboarding Question",
    emojie: "❓",
    category: "settings",
  },
  {
    link: "/hr/employees/offboarding-request",
    hub: "hr",
    module: "employees",
    entity: "offboarding-request",
    name: "Offboarding Request",
    emojie: "📤",
    category: "offboarding",
  },
  {
    link: "/hr/employees/offboarding-task",
    hub: "hr",
    module: "employees",
    entity: "offboarding-task",
    name: "Offboarding Task",
    emojie: "⚙️",
    category: "offboarding",
  },
  {
    link: "/hr/employees/offboarding-template",
    hub: "hr",
    module: "employees",
    entity: "offboarding-template",
    name: "Offboarding Template",
    emojie: "📄",
    category: "settings",
  },
  {
    link: "/hr/employees/settings",
    hub: "hr",
    module: "employees",
    entity: "settings",
    name: "Settings",
    emojie: "🔧",
    category: "settings",
  },
  {
    link: "/hr/leave",
    hub: "hr",
    module: "leave",
    name: "Leave",
    emojie: "🏖️",
    category: "leave",
  },
  {
    link: "/hr/leave/leave-balance",
    hub: "hr",
    module: "leave",
    entity: "leave-balance",
    name: "Leave Balance",
    emojie: "⚖️",
    category: "leave",
  },
  {
    link: "/hr/leave/leave-encashment",
    hub: "hr",
    module: "leave",
    entity: "leave-encashment",
    name: "Leave Encashment",
    emojie: "💲",
    category: "leave",
  },
  {
    link: "/hr/leave/leave-request",
    hub: "hr",
    module: "leave",
    entity: "leave-request",
    name: "Leave Request",
    emojie: "📬",
    category: "leave",
  },
  {
    link: "/hr/leave/settings",
    hub: "hr",
    module: "leave",
    entity: "settings",
    name: "Settings",
    emojie: "🔧",
    category: "settings",
  },
  {
    link: "/hr/leave/settings/holiday",
    hub: "hr",
    module: "leave",
    entity: "holiday",
    name: "Holiday",
    emojie: "🥳",
    category: "settings",
  },
  {
    link: "/hr/leave/settings/leave-type",
    hub: "hr",
    module: "leave",
    entity: "leave-type",
    name: "Leave Type",
    emojie: "🏷️",
    category: "settings",
  },
  {
    link: "/hr/leave/settings/work-schedule",
    hub: "hr",
    module: "leave",
    entity: "work-schedule",
    name: "Work Schedule",
    emojie: "🗓️",
    category: "settings",
  },
  {
    link: "/hr/leave/settings/work-schedule-slot",
    hub: "hr",
    module: "leave",
    entity: "work-schedule-slot",
    name: "Work Schedule Slot",
    emojie: "🕒",
    category: "settings",
  },
  {
    link: "/hr/leave/sick-leave-episode",
    hub: "hr",
    module: "leave",
    entity: "sick-leave-episode",
    name: "Sick Leave Episode",
    emojie: "🤒",
    category: "leave",
  },
  {
    link: "/hr/payroll",
    hub: "hr",
    module: "payroll",
    name: "Payroll",
    emojie: "💳",
    category: "payroll",
  },
  {
    link: "/hr/payroll/bank-accounts",
    hub: "hr",
    module: "payroll",
    entity: "bank-accounts",
    name: "Bank Accounts",
    emojie: "🏦",
    category: "payroll",
  },
  {
    link: "/hr/payroll/generate-single-payslip",
    hub: "hr",
    module: "payroll",
    entity: "generate-single-payslip",
    name: "Generate Single Payslip",
    emojie: "🖨️",
    category: "payroll",
  },
  {
    link: "/hr/payroll/payroll-batches",
    hub: "hr",
    module: "payroll",
    entity: "payroll-batches",
    name: "Payroll Batches",
    emojie: "📦",
    category: "payroll",
  },
  {
    link: "/hr/payroll/payslip-inputs",
    hub: "hr",
    module: "payroll",
    entity: "payslip-inputs",
    name: "Payslip Inputs",
    emojie: "⌨️",
    category: "payroll",
  },
  {
    link: "/hr/payroll/payslips",
    hub: "hr",
    module: "payroll",
    entity: "payslips",
    name: "Payslips",
    emojie: "💵",
    category: "payroll",
  },
  {
    link: "/hr/payroll/pension-policy",
    hub: "hr",
    module: "payroll",
    entity: "pension-policy",
    name: "Pension Policy",
    emojie: "👴",
    category: "settings",
  },
  {
    link: "/hr/payroll/report",
    hub: "hr",
    module: "payroll",
    entity: "report",
    name: "Report",
    emojie: "📈",
    category: "reporting",
  },
  {
    link: "/hr/payroll/settings",
    hub: "hr",
    module: "payroll",
    entity: "settings",
    name: "Settings",
    emojie: "🔧",
    category: "settings",
  },
  {
    link: "/hr/payroll/settings/periods",
    hub: "hr",
    module: "payroll",
    entity: "periods",
    name: "Periods",
    emojie: "📅",
    category: "settings",
  },
  {
    link: "/hr/payroll/settings/salary-rule-categories",
    hub: "hr",
    module: "payroll",
    entity: "salary-rule-categories",
    name: "Salary Rule Categories",
    emojie: "🏷️",
    category: "settings",
  },
  {
    link: "/hr/payroll/settings/salary-rules",
    hub: "hr",
    module: "payroll",
    entity: "salary-rules",
    name: "Salary Rules",
    emojie: "📜",
    category: "settings",
  },
  {
    link: "/hr/payroll/settings/salary-structure",
    hub: "hr",
    module: "payroll",
    entity: "salary-structure",
    name: "Salary Structure",
    emojie: "🏗️",
    category: "settings",
  },
  {
    link: "/hr/payroll/settings/salary-structure-rules",
    hub: "hr",
    module: "payroll",
    entity: "salary-structure-rules",
    name: "Salary Structure Rules",
    emojie: "🧱",
    category: "settings",
  },
  {
    link: "/hr/payroll/tax-bracket",
    hub: "hr",
    module: "payroll",
    entity: "tax-bracket",
    name: "Tax Bracket",
    emojie: "🔢",
    category: "settings",
  },
  {
    link: "/hr/payroll/work-entries",
    hub: "hr",
    module: "payroll",
    entity: "work-entries",
    name: "Work Entries",
    emojie: "📝",
    category: "payroll",
  },
  {
    link: "/hr/performance",
    hub: "hr",
    module: "performance",
    name: "Performance",
    emojie: "🚀",
    category: "performance",
  },
  {
    link: "/hr/performance/appraisalevaluation",
    hub: "hr",
    module: "performance",
    entity: "appraisalevaluation",
    name: "Appraisalevaluation",
    emojie: "⭐",
    category: "performance",
  },
  {
    link: "/hr/performance/appraisalplan",
    hub: "hr",
    module: "performance",
    entity: "appraisalplan",
    name: "Appraisalplan",
    emojie: "🗺️",
    category: "performance",
  },
  {
    link: "/hr/performance/benefitplan",
    hub: "hr",
    module: "performance",
    entity: "benefitplan",
    name: "Benefitplan",
    emojie: "🛡️",
    category: "settings",
  },
  {
    link: "/hr/performance/employeebenefit",
    hub: "hr",
    module: "performance",
    entity: "employeebenefit",
    name: "Employeebenefit",
    emojie: "🍎",
    category: "performance",
  },
  {
    link: "/hr/performance/goal",
    hub: "hr",
    module: "performance",
    entity: "goal",
    name: "Goal",
    emojie: "🎯",
    category: "performance",
  },
  {
    link: "/hr/performance/incident",
    hub: "hr",
    module: "performance",
    entity: "incident",
    name: "Incident",
    emojie: "🚨",
    category: "performance",
  },
  {
    link: "/hr/performance/incidentaction",
    hub: "hr",
    module: "performance",
    entity: "incidentaction",
    name: "Incidentaction",
    emojie: "🛑",
    category: "settings",
  },
  {
    link: "/hr/performance/incidentstatus",
    hub: "hr",
    module: "performance",
    entity: "incidentstatus",
    name: "Incidentstatus",
    emojie: "🚥",
    category: "settings",
  },
  {
    link: "/hr/performance/incidenttype",
    hub: "hr",
    module: "performance",
    entity: "incidenttype",
    name: "Incidenttype",
    emojie: "⚡",
    category: "settings",
  },
  {
    link: "/hr/performance/kpi",
    hub: "hr",
    module: "performance",
    entity: "kpi",
    name: "Kpi",
    emojie: "💯",
    category: "performance",
  },
  {
    link: "/hr/performance/objective",
    hub: "hr",
    module: "performance",
    entity: "objective",
    name: "Objective",
    emojie: "🥅",
    category: "performance",
  },
  {
    link: "/hr/performance/performancecycle",
    hub: "hr",
    module: "performance",
    entity: "performancecycle",
    name: "Performancecycle",
    emojie: "🔄",
    category: "performance",
  },
  {
    link: "/hr/performance/recommendation-rule",
    hub: "hr",
    module: "performance",
    entity: "recommendation-rule",
    name: "Recommendation Rule",
    emojie: "💡",
    category: "settings",
  },
  {
    link: "/hr/performance/template",
    hub: "hr",
    module: "performance",
    entity: "template",
    name: "Template",
    emojie: "📑",
    category: "settings",
  },
];
