import { Modulab } from "./permissions";

export const selfServiceLinks: Modulab[] = [
  {
    link: "/self-service",
    hub: "self-service",
    name: "Self Service",
    emojie: "👤",
    category: "navigation", // Kept as 'navigation' as it's the root/hub link
  },
  {
    link: "/self-service/appraisal-evaluation",
    hub: "self-service",
    module: "performance",
    entity: "appraisal-evaluation",
    name: "Appraisal Evaluation",
    emojie: "📝",
    category: "performance",
  },
  {
    link: "/self-service/appraisal-evaluation",
    hub: "self-service",
    module: "performance",
    name: "Appraisal Evaluation",
    emojie: "📝",
    category: "performance",
  },
  {
    link: "/self-service/attendance",
    hub: "self-service",
    module: "attendance",
    entity: "attendance",
    name: "Attendance",
    emojie: "⏰",
    category: "attendance",
  },
  {
    link: "/self-service/attendance",
    hub: "self-service",
    module: "attendance",
    name: "Attendance",
    emojie: "⏰",
    category: "attendance",
  },
  {
    link: "/self-service/benefits",
    hub: "self-service",
    module: "employee",
    entity: "benefits",
    name: "Benefits",
    emojie: "🎁",
    category: "employee",
  },
  {
    link: "/self-service/benefits",
    hub: "self-service",
    module: "employee",
    name: "Benefits",
    emojie: "🎁",
    category: "employee",
  },
  {
    link: "/self-service/documents",
    hub: "self-service",
    module: "employee",
    entity: "documents",
    name: "Documents",
    emojie: "📜",
    category: "employee",
  },
  {
    link: "/self-service/exits",
    hub: "self-service",
    module: "employee",
    entity: "exits",
    name: "Exits",
    emojie: "🚪",
    category: "employee",
  },
  {
    link: "/self-service/job-req",
    hub: "self-service",
    module: "employee", // Mapped from 'recruitment' to 'employee'
    entity: "job-req",
    name: "Job Req",
    emojie: "💼",
    category: "employee", // Mapped from 'recruitment' to 'employee'
  },
  {
    link: "/self-service/jobs",
    hub: "self-service",
    module: "employee", // Mapped from 'recruitment' to 'employee'
    entity: "jobs",
    name: "Jobs",
    emojie: "🔍",
    category: "employee", // Mapped from 'recruitment' to 'employee'
  },
  {
    link: "/self-service/leaves",
    hub: "self-service",
    module: "leave",
    name: "Leaves",
    emojie: "🌴",
    category: "leave",
  },
  {
    link: "/self-service/leaves",
    hub: "self-service",
    module: "leave",
    entity: "leaves",
    name: "Leaves",
    emojie: "🌴",
    category: "leave",
  },
  {
    link: "/self-service/payslips",
    hub: "self-service",
    module: "payroll",
    name: "Payslips",
    emojie: "💵",
    category: "payroll",
  },
  {
    link: "/self-service/payslips",
    hub: "self-service",
    module: "payroll",
    entity: "payslips",
    name: "Payslips",
    emojie: "💵",
    category: "payroll",
  },
  {
    link: "/self-service/personal-info",
    hub: "self-service",
    module: "employee",
    entity: "personal-info",
    name: "Personal Info",
    emojie: "ℹ️",
    category: "employee",
  },
  {
    link: "/self-service/profile",
    hub: "self-service",
    module: "employee",
    entity: "profile",
    name: "Profile",
    emojie: "🌟",
    category: "employee",
  },
  {
    link: "/self-service/survey",
    hub: "self-service",
    module: "training",
    name: "Survey",
    emojie: "📋",
    category: "training",
  },
  {
    link: "/self-service/survey",
    hub: "self-service",
    module: "training",
    entity: "survey",
    name: "Survey",
    emojie: "📋",
    category: "training",
  },
  {
    link: "/self-service/training-performance",
    hub: "self-service",
    module: "training",
    entity: "training-performance",
    name: "Training Performance",
    emojie: "🎓",
    category: "training",
  },
];
