export type Modulab = {
  link: string;
  hub: string;
  module?: string;
  category?: string;
  entity?: string;
  name: string;
  emojie: string;
};

export const trainingModulabs: Modulab[] = [
  {
    link: "/hr/training",
    hub: "hr",
    module: "training",
    name: "Training",
    emojie: "🎓",
    category: "training",
  },
  {
    link: "/hr/training/settings/tna-survey-template",
    hub: "hr",
    module: "training",
    entity: "tna-survey-template",
    name: "TNA Survey Template",
    emojie: "📋",
    category: "settings",
  },
  {
    link: "/hr/training/tna-answer",
    hub: "hr",
    module: "training",
    entity: "tna-answer",
    name: "TNA Answer",
    emojie: "💬",
    category: "training",
  },
  {
    link: "/hr/training/tna-question",
    hub: "hr",
    module: "training",
    entity: "tna-question",
    name: "TNA Question",
    emojie: "❓",
    category: "training",
  },
  {
    link: "/hr/training/tna-survey",
    hub: "hr",
    module: "training",
    entity: "tna-survey",
    name: "TNA Survey",
    emojie: "📝",
    category: "training",
  },
  {
    link: "/hr/training/trainer",
    hub: "hr",
    module: "training",
    entity: "trainer",
    name: "Trainer",
    emojie: "👨‍🏫",
    category: "training",
  },
  {
    link: "/hr/training/training-attendance",
    hub: "hr",
    module: "training",
    entity: "training-attendance",
    name: "Training Attendance",
    emojie: "✅",
    category: "training",
  },
  {
    link: "/hr/training/training-certificate",
    hub: "hr",
    module: "training",
    entity: "training-certificate",
    name: "Training Certificate",
    emojie: "🏅",
    category: "training",
  },
  {
    link: "/hr/training/training-program-plan",
    hub: "hr",
    module: "training",
    entity: "training-program-plan",
    name: "Training Program Plan",
    emojie: "🗺️",
    category: "training",
  },
  {
    link: "/hr/training/training-record",
    hub: "hr",
    module: "training",
    entity: "training-record",
    name: "Training Record",
    emojie: "📜",
    category: "training",
  },
  {
    link: "/hr/training/training-request",
    hub: "hr",
    module: "training",
    entity: "training-request",
    name: "Training Request",
    emojie: "📧",
    category: "training",
  },
  {
    link: "/hr/training/training-request-appraisal-evaluation",
    hub: "hr",
    module: "training",
    entity: "training-request-appraisal-evaluation",
    name: "Training Request Appraisal Evaluation",
    emojie: "📊",
    category: "training",
  },
  {
    link: "/hr/training/training-request-bundle",
    hub: "hr",
    module: "training",
    entity: "training-request-bundle",
    name: "Training Request Bundle",
    emojie: "📦",
    category: "training",
  },
  {
    link: "/hr/training/training-request-category",
    hub: "hr",
    module: "training",
    entity: "training-request-category",
    name: "Training Request Category",
    emojie: "🏷️",
    category: "training",
  },
  {
    link: "/hr/training/training-request-target-employee",
    hub: "hr",
    module: "training",
    entity: "training-request-target-employee",
    name: "Training Request Target Employee",
    emojie: "🎯",
    category: "training",
  },
  {
    link: "/hr/training/training-request-tna",
    hub: "hr",
    module: "training",
    entity: "training-request-tna",
    name: "Training Request TNA",
    emojie: "📝",
    category: "training",
  },
  {
    link: "/hr/training/training-session",
    hub: "hr",
    module: "training",
    entity: "training-session",
    name: "Training Session",
    emojie: "📅",
    category: "training",
  },
  {
    link: "/hr/training/training-session-trainer",
    hub: "hr",
    module: "training",
    entity: "training-session-trainer",
    name: "Training Session Trainer",
    emojie: "👤",
    category: "training",
  },
];
